/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import com.mycompany.dao.DBConnect;
import com.mycompany.model.MayTinh;
import java.util.List;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;

import com.mycompany.controller.QuanLyMayTinhController;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author Admin
 */
public class QuanLySanPham extends javax.swing.JPanel {

    /**
     * Creates new form QuanLySanPham
     */
    public QuanLySanPham() {
        initComponents();
        QuanLyMayTinhController controller = new QuanLyMayTinhController(txtMaMayTinh,txtTenMayTinh,jcbThoiGianBaoHanh,txtXuatXu,txtGiaBan,txtSoLuong,jpnTableQLSP);
        controller.setDataToTable();
        jpnChucNangSanPham.validate();
        jpnChucNangSanPham.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpnThongTinSanPham = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMaMayTinh = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTenMayTinh = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jcbThoiGianBaoHanh = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtXuatXu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGiaBan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        btnSinhMaMayTinh = new javax.swing.JButton();
        jpnTimKiemSanPham = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtTimKiemMMT = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTimKiemTMT = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTimKiemXuatXu = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTimKiemGiaTu = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTimKiemGiaDen = new javax.swing.JTextField();
        btnTimKiemSanPham = new javax.swing.JButton();
        jpnTableQLSP = new javax.swing.JPanel();
        jpnChucNangSanPham = new javax.swing.JPanel();
        btnThemSanPham = new javax.swing.JButton();
        btnSuaSanPham = new javax.swing.JButton();
        btnXoaSanPham = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();

        setBackground(java.awt.Color.white);
        setForeground(java.awt.Color.black);

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.red);
        jLabel1.setText("Quản Lý Sản Phẩm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(470, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(385, 385, 385))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnThongTinSanPham.setBackground(java.awt.Color.white);
        jpnThongTinSanPham.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12), java.awt.Color.black)); // NOI18N
        jpnThongTinSanPham.setForeground(java.awt.Color.black);

        jLabel2.setForeground(java.awt.Color.black);
        jLabel2.setText("Mã máy tính");

        txtMaMayTinh.setBackground(java.awt.Color.white);
        txtMaMayTinh.setForeground(java.awt.Color.black);
        txtMaMayTinh.setOpaque(true);
        txtMaMayTinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMaMayTinhMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtMaMayTinhMouseExited(evt);
            }
        });
        txtMaMayTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaMayTinhActionPerformed(evt);
            }
        });

        jLabel3.setForeground(java.awt.Color.black);
        jLabel3.setText("Tên máy tính");

        txtTenMayTinh.setBackground(java.awt.Color.white);
        txtTenMayTinh.setForeground(java.awt.Color.black);
        txtTenMayTinh.setOpaque(true);
        txtTenMayTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenMayTinhActionPerformed(evt);
            }
        });

        jLabel4.setForeground(java.awt.Color.black);
        jLabel4.setText("Thời gian bảo hành");

        jcbThoiGianBaoHanh.setBackground(java.awt.Color.white);
        jcbThoiGianBaoHanh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jcbThoiGianBaoHanh.setForeground(java.awt.Color.black);
        jcbThoiGianBaoHanh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6 tháng ", "12 tháng", "24 tháng", "36 tháng", "48 tháng", " " }));
        jcbThoiGianBaoHanh.setOpaque(true);
        jcbThoiGianBaoHanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbThoiGianBaoHanhActionPerformed(evt);
            }
        });

        jLabel5.setForeground(java.awt.Color.black);
        jLabel5.setText("Xuất xứ");

        txtXuatXu.setBackground(java.awt.Color.white);
        txtXuatXu.setForeground(java.awt.Color.black);

        jLabel6.setBackground(java.awt.Color.white);
        jLabel6.setForeground(java.awt.Color.black);
        jLabel6.setText("Giá bán");

        txtGiaBan.setBackground(java.awt.Color.white);
        txtGiaBan.setForeground(java.awt.Color.black);

        jLabel7.setBackground(java.awt.Color.white);
        jLabel7.setForeground(java.awt.Color.black);
        jLabel7.setText("Số lượng");

        txtSoLuong.setBackground(java.awt.Color.white);
        txtSoLuong.setForeground(java.awt.Color.black);

        btnSinhMaMayTinh.setBackground(java.awt.Color.white);
        btnSinhMaMayTinh.setForeground(java.awt.Color.black);
        btnSinhMaMayTinh.setText("+");
        btnSinhMaMayTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinhMaMayTinhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnThongTinSanPhamLayout = new javax.swing.GroupLayout(jpnThongTinSanPham);
        jpnThongTinSanPham.setLayout(jpnThongTinSanPhamLayout);
        jpnThongTinSanPhamLayout.setHorizontalGroup(
            jpnThongTinSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnThongTinSanPhamLayout.createSequentialGroup()
                .addGroup(jpnThongTinSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnThongTinSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtTenMayTinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcbThoiGianBaoHanh, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnThongTinSanPhamLayout.createSequentialGroup()
                        .addGroup(jpnThongTinSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaMayTinh))
                        .addGap(5, 5, 5)
                        .addComponent(btnSinhMaMayTinh)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(jpnThongTinSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtXuatXu)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaBan)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(txtSoLuong))
                .addGap(48, 48, 48))
        );
        jpnThongTinSanPhamLayout.setVerticalGroup(
            jpnThongTinSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongTinSanPhamLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jpnThongTinSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnThongTinSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtXuatXu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSinhMaMayTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaMayTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnThongTinSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnThongTinSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenMayTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jpnThongTinSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnThongTinSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbThoiGianBaoHanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnTimKiemSanPham.setBackground(java.awt.Color.white);
        jpnTimKiemSanPham.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm Kiếm Sản Phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12), java.awt.Color.black)); // NOI18N

        jLabel8.setBackground(java.awt.Color.white);
        jLabel8.setForeground(java.awt.Color.black);
        jLabel8.setText("Mã máy tính");

        txtTimKiemMMT.setBackground(java.awt.Color.white);
        txtTimKiemMMT.setForeground(java.awt.Color.black);

        jLabel9.setBackground(java.awt.Color.white);
        jLabel9.setForeground(java.awt.Color.black);
        jLabel9.setText("Tên máy tính");

        txtTimKiemTMT.setBackground(java.awt.Color.white);
        txtTimKiemTMT.setForeground(java.awt.Color.black);

        jLabel10.setBackground(java.awt.Color.white);
        jLabel10.setForeground(java.awt.Color.black);
        jLabel10.setText("Xuất xứ");

        txtTimKiemXuatXu.setBackground(java.awt.Color.white);
        txtTimKiemXuatXu.setForeground(java.awt.Color.black);

        jLabel11.setBackground(java.awt.Color.white);
        jLabel11.setForeground(java.awt.Color.black);
        jLabel11.setText("Giá từ");

        txtTimKiemGiaTu.setBackground(java.awt.Color.white);
        txtTimKiemGiaTu.setForeground(java.awt.Color.black);

        jLabel12.setBackground(java.awt.Color.white);
        jLabel12.setForeground(java.awt.Color.black);
        jLabel12.setText("Đến");

        txtTimKiemGiaDen.setBackground(java.awt.Color.white);
        txtTimKiemGiaDen.setForeground(java.awt.Color.black);

        btnTimKiemSanPham.setBackground(java.awt.Color.white);
        btnTimKiemSanPham.setForeground(java.awt.Color.black);
        btnTimKiemSanPham.setText("Tìm Kiếm");

        javax.swing.GroupLayout jpnTimKiemSanPhamLayout = new javax.swing.GroupLayout(jpnTimKiemSanPham);
        jpnTimKiemSanPham.setLayout(jpnTimKiemSanPhamLayout);
        jpnTimKiemSanPhamLayout.setHorizontalGroup(
            jpnTimKiemSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTimKiemSanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnTimKiemSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnTimKiemSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnTimKiemSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnTimKiemSanPhamLayout.createSequentialGroup()
                        .addComponent(txtTimKiemGiaTu, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTimKiemTMT, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiemMMT, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiemXuatXu, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jpnTimKiemSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTimKiemGiaDen, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jpnTimKiemSanPhamLayout.setVerticalGroup(
            jpnTimKiemSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTimKiemSanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnTimKiemSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiemMMT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpnTimKiemSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnTimKiemSanPhamLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jpnTimKiemSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTimKiemTMT, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnTimKiemSanPhamLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnTimKiemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jpnTimKiemSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTimKiemXuatXu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jpnTimKiemSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnTimKiemSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtTimKiemGiaTu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnTimKiemSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTimKiemGiaDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)))
                .addGap(28, 28, 28))
        );

        jpnTableQLSP.setBackground(java.awt.Color.white);
        jpnTableQLSP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12), java.awt.Color.black)); // NOI18N
        jpnTableQLSP.setForeground(java.awt.Color.black);

        javax.swing.GroupLayout jpnTableQLSPLayout = new javax.swing.GroupLayout(jpnTableQLSP);
        jpnTableQLSP.setLayout(jpnTableQLSPLayout);
        jpnTableQLSPLayout.setHorizontalGroup(
            jpnTableQLSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1052, Short.MAX_VALUE)
        );
        jpnTableQLSPLayout.setVerticalGroup(
            jpnTableQLSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 231, Short.MAX_VALUE)
        );

        jpnChucNangSanPham.setBackground(java.awt.Color.white);

        btnThemSanPham.setBackground(java.awt.Color.white);
        btnThemSanPham.setForeground(java.awt.Color.black);
        btnThemSanPham.setText("Thêm");
        btnThemSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemSanPhamMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThemSanPhamMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnThemSanPhamMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnThemSanPhamMouseReleased(evt);
            }
        });
        btnThemSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSanPhamActionPerformed(evt);
            }
        });

        btnSuaSanPham.setBackground(java.awt.Color.white);
        btnSuaSanPham.setForeground(java.awt.Color.black);
        btnSuaSanPham.setText("Sửa");
        btnSuaSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaSanPhamMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSuaSanPhamMouseExited(evt);
            }
        });
        btnSuaSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaSanPhamActionPerformed(evt);
            }
        });

        btnXoaSanPham.setBackground(java.awt.Color.white);
        btnXoaSanPham.setForeground(java.awt.Color.black);
        btnXoaSanPham.setText("Xóa");
        btnXoaSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaSanPhamMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXoaSanPhamMouseExited(evt);
            }
        });
        btnXoaSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSanPhamActionPerformed(evt);
            }
        });

        btnLamMoi.setBackground(java.awt.Color.white);
        btnLamMoi.setForeground(java.awt.Color.black);
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLamMoiMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLamMoiMouseExited(evt);
            }
        });
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnChucNangSanPhamLayout = new javax.swing.GroupLayout(jpnChucNangSanPham);
        jpnChucNangSanPham.setLayout(jpnChucNangSanPhamLayout);
        jpnChucNangSanPhamLayout.setHorizontalGroup(
            jpnChucNangSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnChucNangSanPhamLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(btnThemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(btnSuaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXoaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
        jpnChucNangSanPhamLayout.setVerticalGroup(
            jpnChucNangSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnChucNangSanPhamLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jpnChucNangSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemSanPham)
                    .addComponent(btnSuaSanPham)
                    .addComponent(btnXoaSanPham)
                    .addComponent(btnLamMoi))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpnChucNangSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnTableQLSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpnThongTinSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpnTimKiemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnThongTinSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnTimKiemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnTableQLSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnChucNangSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcbThoiGianBaoHanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbThoiGianBaoHanhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbThoiGianBaoHanhActionPerformed

    private void txtTenMayTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenMayTinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenMayTinhActionPerformed

    private void txtMaMayTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaMayTinhActionPerformed
        // TODO add your handling code here:
        if(txtMaMayTinh.getText().equals(""))
        {
            System.out.println(txtMaMayTinh.getText().length());
            txtMaMayTinh.setBackground(Color.red);
        }
        else
        {
            txtMaMayTinh.setBackground(Color.white);
        }
    }//GEN-LAST:event_txtMaMayTinhActionPerformed

    private void btnSinhMaMayTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinhMaMayTinhActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnSinhMaMayTinhActionPerformed

    private void btnThemSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSanPhamActionPerformed
         try {
            String errors = "";
            if(txtMaMayTinh.getText().equals(""))
            {
                errors += "Mã máy tính chưa được nhập\n";
                txtMaMayTinh.setBackground(Color.red);
            }
            else    txtMaMayTinh.setBackground(Color.WHITE);
           
            
            if(txtTenMayTinh.getText().equals(""))
            {
                errors+= "Tên máy tính chưa được nhập\n";
                txtTenMayTinh.setBackground(Color.red);
            }
            else txtTenMayTinh.setBackground(Color.white);
            
            String Item = (String) jcbThoiGianBaoHanh.getSelectedItem();
            if(Item.length()==1)
            {
                errors+= "Thời gian bảo hành chưa được nhập\n";
                jcbThoiGianBaoHanh.setBackground(Color.red);
            }
            else jcbThoiGianBaoHanh.setBackground(Color.white);
            
            if(txtXuatXu.getText().equals(""))
            {
                errors+= "Xuất xứ chưa được nhập\n";
                txtXuatXu.setBackground(Color.red);
            }
            else txtXuatXu.setBackground(Color.white);
            
            if(txtGiaBan.getText().equals(""))
            {
                errors+= "Giá bán chưa được nhập\n";
                txtGiaBan.setBackground(Color.red);
            }
            else txtGiaBan.setBackground(Color.white);
            
            if(txtSoLuong.getText().equals(""))
            {
                errors+= "Số lượng chưa được nhập";
                txtSoLuong.setBackground(Color.red);
            }
            else txtSoLuong.setBackground(Color.white);
            
            if(!errors.isEmpty())
            {
                System.out.println("hello");
                JOptionPane.showMessageDialog(this, errors);
            }
            else
            {
                //System.out.println("112");
                String sql = "INSERT INTO dbo.SanPham(ma_may_tinh,ten_may_tinh,xuat_xu,thoi_gian_bao_hanh,so_luong,gia_ban)    " + " VALUES(?, ?, ?, ? , ? ,  ? ) ";
                try (Connection c = DBConnect.getConnection();
                PreparedStatement ps = c.prepareCall(sql);)
                {
                    ps.setString(1, txtMaMayTinh.getText());
                    ps.setString(2, txtTenMayTinh.getText());
                    ps.setString(3,txtXuatXu.getText());
                    ps.setString(4, "15thang");
                    ps.setInt(5, Integer.valueOf(txtSoLuong.getText()) );
                    ps.setInt(6, Integer.valueOf( txtGiaBan.getText() ) );
                    System.out.println( ps.executeUpdate(sql) );
                } catch (Exception ex) {System.out.println(ex.getMessage());}
                
                System.out.println("hello");
                JOptionPane.showConfirmDialog(this, "Bạn chắc chắn chứ aa");
            }
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Erorr " + e.getMessage());
        }
   
    }//GEN-LAST:event_btnThemSanPhamActionPerformed

    private void btnThemSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemSanPhamMouseClicked
        // TODO add your handling code here:
        
        btnThemSanPham.setBackground(Color.red);
        btnThemSanPham.setForeground(Color.WHITE);
        
        try {
            Thread.sleep(200);
        } catch (InterruptedException ex) {
            //Logger.getLogger(QuanLySanPham.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        btnThemSanPham.setBackground(Color.white);
        btnThemSanPham.setForeground(Color.black);
        //ChangeButtonBackGroud(btnThemSanPham);
    }//GEN-LAST:event_btnThemSanPhamMouseClicked

    private void btnThemSanPhamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemSanPhamMouseExited
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnThemSanPhamMouseExited

    private void btnSuaSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaSanPhamActionPerformed
        //btnSuaSanPham.setBackground(Color.RED);
    }//GEN-LAST:event_btnSuaSanPhamActionPerformed

    private void btnSuaSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaSanPhamMouseClicked
         btnSuaSanPham.setBackground(Color.RED);
         btnSuaSanPham.setForeground(Color.WHITE);
        try {
            Thread.sleep(200);
        } catch (InterruptedException ex) {
            Logger.getLogger(QuanLySanPham.class.getName()).log(Level.SEVERE, null, ex);
        }
        btnSuaSanPham.setBackground(Color.white);
        btnSuaSanPham.setForeground(Color.black);
    }//GEN-LAST:event_btnSuaSanPhamMouseClicked

    private void btnSuaSanPhamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaSanPhamMouseExited
        // TODO add your handling code here:
         //btnSuaSanPham.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnSuaSanPhamMouseExited

    private void btnXoaSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaSanPhamActionPerformed
        //btnXoaSanPham.setBackground(Color.RED);
    }//GEN-LAST:event_btnXoaSanPhamActionPerformed

    private void btnXoaSanPhamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaSanPhamMouseExited
        //btnXoaSanPham.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnXoaSanPhamMouseExited

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        txtMaMayTinh.setText("");
        txtTenMayTinh.setText("");
        jcbThoiGianBaoHanh.setSelectedIndex(0);
        txtXuatXu.setText("");
        txtGiaBan.setText("");
        txtSoLuong.setText("");
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnLamMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLamMoiMouseClicked
        btnLamMoi.setBackground(Color.RED);
        btnLamMoi.setForeground(Color.WHITE);
        try {
            Thread.sleep(200);
        } catch (InterruptedException ex) {
            Logger.getLogger(QuanLySanPham.class.getName()).log(Level.SEVERE, null, ex);
        }
         btnLamMoi.setBackground(Color.white);
         btnLamMoi.setForeground(Color.black);
    }//GEN-LAST:event_btnLamMoiMouseClicked

    private void btnLamMoiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLamMoiMouseExited
        
    }//GEN-LAST:event_btnLamMoiMouseExited

    private void btnThemSanPhamMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemSanPhamMouseReleased
        // TODO add your handling code here:
        //btnThemSanPham.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnThemSanPhamMouseReleased

    private void btnThemSanPhamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemSanPhamMousePressed
        // TODO add your handling code here:
        //btnThemSanPham.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnThemSanPhamMousePressed

    private void btnXoaSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaSanPhamMouseClicked
       btnXoaSanPham.setBackground(Color.red);
       btnXoaSanPham.setForeground(Color.WHITE);
        try {
            Thread.sleep(200);
        } catch (InterruptedException ex) {
            Logger.getLogger(QuanLySanPham.class.getName()).log(Level.SEVERE, null, ex);
        }
        btnXoaSanPham.setBackground(Color.white);
       btnXoaSanPham.setForeground(Color.black);
    }//GEN-LAST:event_btnXoaSanPhamMouseClicked

    private void txtMaMayTinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMaMayTinhMouseClicked
        // TODO add your handling code here:
        if(txtMaMayTinh.getText().equals(""))
        {
            txtMaMayTinh.setBackground(Color.red);
        }
        else
        {
            txtMaMayTinh.setBackground(Color.white);
        }
    }//GEN-LAST:event_txtMaMayTinhMouseClicked
    
    private void txtMaMayTinhMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMaMayTinhMouseExited
        // TODO add your handling code here:
        if(txtMaMayTinh.getText().equals(""))
        {
            txtMaMayTinh.setBackground(Color.red);
        }
        else
        {
            txtMaMayTinh.setBackground(Color.white);
        }
    }//GEN-LAST:event_txtMaMayTinhMouseExited

    public JTextField getTxtGiaBan() {
        return txtGiaBan;
    }

    public void setTxtGiaBan(JTextField txtGiaBan) {
        this.txtGiaBan = txtGiaBan;
    }

    public JTextField getTxtMaMayTinh() {
        return txtMaMayTinh;
    }

    public void setTxtMaMayTinh(JTextField txtMaMayTinh) {
        this.txtMaMayTinh = txtMaMayTinh;
    }

    public JTextField getTxtSoLuong() {
        return txtSoLuong;
    }

    public void setTxtSoLuong(JTextField txtSoLuong) {
        this.txtSoLuong = txtSoLuong;
    }

    public JTextField getTxtTenMayTinh() {
        return txtTenMayTinh;
    }

    public void setTxtTenMayTinh(JTextField txtTenMayTinh) {
        this.txtTenMayTinh = txtTenMayTinh;
    }

    public JTextField getTxtXuatXu() {
        return txtXuatXu;
    }

    public void setTxtXuatXu(JTextField txtXuatXu) {
        this.txtXuatXu = txtXuatXu;
    }
    
    
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSinhMaMayTinh;
    private javax.swing.JButton btnSuaSanPham;
    private javax.swing.JButton btnThemSanPham;
    private javax.swing.JButton btnTimKiemSanPham;
    private javax.swing.JButton btnXoaSanPham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcbThoiGianBaoHanh;
    private javax.swing.JPanel jpnChucNangSanPham;
    private javax.swing.JPanel jpnTableQLSP;
    private javax.swing.JPanel jpnThongTinSanPham;
    private javax.swing.JPanel jpnTimKiemSanPham;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtMaMayTinh;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenMayTinh;
    private javax.swing.JTextField txtTimKiemGiaDen;
    private javax.swing.JTextField txtTimKiemGiaTu;
    private javax.swing.JTextField txtTimKiemMMT;
    private javax.swing.JTextField txtTimKiemTMT;
    private javax.swing.JTextField txtTimKiemXuatXu;
    private javax.swing.JTextField txtXuatXu;
    // End of variables declaration//GEN-END:variables
}
