/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.view;

import com.mycompany.controller.QuanLyHoaDonBanController;
import com.mycompany.dao.DBConnect;
import com.mycompany.dao.HoaDonDAO;
import com.mycompany.dao.HoaDonDAOImpl;
import com.mycompany.dao.KhachHangDAO;
import com.mycompany.dao.KhachHangDAOImpl;
import com.mycompany.dao.NhanVienDAOImpl;
import com.mycompany.dao.NhanVienDao;
import com.mycompany.model.HoaDonBan;
import com.mycompany.model.KhachHang;
import com.mycompany.model.NhanVien;
import com.mycompany.service.HoaDonBanService;
import com.mycompany.service.HoaDonBanServiceImpl;
import com.mycompany.utility.ClassTableModel;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class jpnHoaDonBan extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyHoaDon
     */
    
    public jpnHoaDonBan(JComboBox<String> jcbHinhThucThanhToan, JTextField txtMaHoaDon, JTextField txtMaNhanVien, JTextField txtNgayBan, JTextField txtSDTkhachHang, JTextField txtTenKhachHang,JButton btnQuanLyKhachHang,JPanel jpnRoot) {
        initComponents();
        this.jcbHinhThucThanhToan = jcbHinhThucThanhToan;
        this.txtMaHoaDon = txtMaHoaDon;
        this.txtMaNhanVien = txtMaNhanVien;
        this.txtNgayBan = txtNgayBan;
        this.txtSDTkhachHang = txtSDTkhachHang;
        this.txtTenKhachHang = txtTenKhachHang;
        this.btnQuanLyKhachHang = btnQuanLyKhachHang;
        this.jpnRoot = jpnRoot;
    }
    QuanLyHoaDonBanController controller;
    public jpnHoaDonBan() {
        initComponents();
        controller = new QuanLyHoaDonBanController(txtMaHoaDon, txtMaNhanVien, txtNgayBan, txtSDTkhachHang, txtTenKhachHang, jcbHinhThucThanhToan, jpnTableDanhSachHoaDon);
        controller.setDataToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSDTkhachHang = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMaHoaDon = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMaNhanVien = new javax.swing.JTextField();
        txtTenKhachHang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNgayBan = new javax.swing.JTextField();
        jcbHinhThucThanhToan = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btnQuanLyKhachHang = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtTimKiemDenNgay = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTimKiemTuNgay = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTimKiemSDTkhachHang = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTimKiemMaNhanVien = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTimKiemMaHoaDon = new javax.swing.JTextField();
        btnTimKiemHoaDon = new javax.swing.JButton();
        jpnTableDanhSachHoaDon = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnThemHoaDon = new javax.swing.JButton();
        btnXoaHoaDon = new javax.swing.JButton();
        btnLamMoiHoaDon = new javax.swing.JButton();
        btnSuaHoaDon = new javax.swing.JButton();

        jpnRoot.setBackground(java.awt.Color.white);

        jPanel2.setBackground(java.awt.Color.white);
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif.bold", 1, 13), java.awt.Color.black)); // NOI18N
        jPanel2.setForeground(java.awt.Color.black);

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setForeground(java.awt.Color.black);
        jLabel1.setText("Mã hóa đơn");

        txtSDTkhachHang.setBackground(java.awt.Color.white);
        txtSDTkhachHang.setForeground(java.awt.Color.black);
        txtSDTkhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSDTkhachHangMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSDTkhachHangMouseExited(evt);
            }
        });
        txtSDTkhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTkhachHangActionPerformed(evt);
            }
        });

        jLabel2.setBackground(java.awt.Color.white);
        jLabel2.setForeground(java.awt.Color.black);
        jLabel2.setText("Mã nhân viên");

        txtMaHoaDon.setBackground(java.awt.Color.white);
        txtMaHoaDon.setForeground(java.awt.Color.black);

        jLabel3.setBackground(java.awt.Color.white);
        jLabel3.setForeground(java.awt.Color.black);
        jLabel3.setText("Tên khách hàng");

        txtMaNhanVien.setBackground(java.awt.Color.white);
        txtMaNhanVien.setForeground(java.awt.Color.black);

        txtTenKhachHang.setBackground(java.awt.Color.white);
        txtTenKhachHang.setForeground(java.awt.Color.black);

        jLabel5.setBackground(java.awt.Color.white);
        jLabel5.setForeground(java.awt.Color.black);
        jLabel5.setText("Ngày bán");

        txtNgayBan.setBackground(java.awt.Color.white);
        txtNgayBan.setForeground(java.awt.Color.black);

        jcbHinhThucThanhToan.setBackground(java.awt.Color.white);
        jcbHinhThucThanhToan.setEditable(true);
        jcbHinhThucThanhToan.setForeground(java.awt.Color.black);
        jcbHinhThucThanhToan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Tiền mặt", "ATM/Banking", "Trả góp", " " }));

        jLabel6.setBackground(java.awt.Color.white);
        jLabel6.setForeground(java.awt.Color.black);
        jLabel6.setText("Hình thức thanh toán");

        btnQuanLyKhachHang.setBackground(java.awt.Color.lightGray);
        btnQuanLyKhachHang.setForeground(java.awt.Color.black);
        btnQuanLyKhachHang.setText("Quản lý khách hàng");
        btnQuanLyKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyKhachHangActionPerformed(evt);
            }
        });

        jLabel7.setBackground(java.awt.Color.white);
        jLabel7.setForeground(java.awt.Color.black);
        jLabel7.setText("SDT Khách hàng");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(txtNgayBan)
                    .addComponent(txtMaHoaDon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jcbHinhThucThanhToan, javax.swing.GroupLayout.Alignment.LEADING, 0, 157, Short.MAX_VALUE)
                            .addComponent(txtSDTkhachHang, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenKhachHang, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(59, 59, 59))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(293, Short.MAX_VALUE)
                .addComponent(btnQuanLyKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSDTkhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgayBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbHinhThucThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnQuanLyKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(java.awt.Color.white);
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif.bold", 1, 13), java.awt.Color.black)); // NOI18N
        jPanel3.setForeground(java.awt.Color.black);

        jLabel4.setBackground(java.awt.Color.white);
        jLabel4.setForeground(java.awt.Color.black);
        jLabel4.setText("Từ ngày ");

        txtTimKiemDenNgay.setBackground(java.awt.Color.white);
        txtTimKiemDenNgay.setForeground(java.awt.Color.black);

        jLabel8.setBackground(java.awt.Color.white);
        jLabel8.setForeground(java.awt.Color.black);
        jLabel8.setText("Đến ngày");

        txtTimKiemTuNgay.setBackground(java.awt.Color.white);
        txtTimKiemTuNgay.setForeground(java.awt.Color.black);

        jLabel9.setBackground(java.awt.Color.white);
        jLabel9.setForeground(java.awt.Color.black);
        jLabel9.setText("Mã hóa đơn");

        txtTimKiemSDTkhachHang.setBackground(java.awt.Color.white);
        txtTimKiemSDTkhachHang.setForeground(java.awt.Color.black);

        jLabel10.setBackground(java.awt.Color.white);
        jLabel10.setForeground(java.awt.Color.black);
        jLabel10.setText("Mã nhân viên");

        txtTimKiemMaNhanVien.setBackground(java.awt.Color.white);
        txtTimKiemMaNhanVien.setForeground(java.awt.Color.black);

        jLabel11.setBackground(java.awt.Color.white);
        jLabel11.setForeground(java.awt.Color.black);
        jLabel11.setText("SDT Khách hàng");

        txtTimKiemMaHoaDon.setBackground(java.awt.Color.white);
        txtTimKiemMaHoaDon.setForeground(java.awt.Color.black);

        btnTimKiemHoaDon.setBackground(java.awt.Color.lightGray);
        btnTimKiemHoaDon.setForeground(java.awt.Color.black);
        btnTimKiemHoaDon.setText("Tìm kiếm");
        btnTimKiemHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemHoaDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txtTimKiemSDTkhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(txtTimKiemMaHoaDon))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTimKiemTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(4, 4, 4)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTimKiemMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTimKiemDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 357, Short.MAX_VALUE)
                                .addComponent(btnTimKiemHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTimKiemDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtTimKiemTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTimKiemMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTimKiemMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addGap(61, 61, 61)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtTimKiemSDTkhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnTimKiemHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpnTableDanhSachHoaDon.setBackground(java.awt.Color.white);
        jpnTableDanhSachHoaDon.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif.bold", 1, 13), java.awt.Color.black)); // NOI18N
        jpnTableDanhSachHoaDon.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout jpnTableDanhSachHoaDonLayout = new javax.swing.GroupLayout(jpnTableDanhSachHoaDon);
        jpnTableDanhSachHoaDon.setLayout(jpnTableDanhSachHoaDonLayout);
        jpnTableDanhSachHoaDonLayout.setHorizontalGroup(
            jpnTableDanhSachHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnTableDanhSachHoaDonLayout.setVerticalGroup(
            jpnTableDanhSachHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );

        jPanel5.setBackground(java.awt.Color.white);
        jPanel5.setForeground(java.awt.Color.black);

        btnThemHoaDon.setBackground(java.awt.Color.white);
        btnThemHoaDon.setForeground(java.awt.Color.black);
        btnThemHoaDon.setText("Thêm");
        btnThemHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemHoaDonActionPerformed(evt);
            }
        });

        btnXoaHoaDon.setBackground(java.awt.Color.white);
        btnXoaHoaDon.setForeground(java.awt.Color.black);
        btnXoaHoaDon.setText("Xóa");
        btnXoaHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaHoaDonActionPerformed(evt);
            }
        });

        btnLamMoiHoaDon.setBackground(java.awt.Color.white);
        btnLamMoiHoaDon.setForeground(java.awt.Color.black);
        btnLamMoiHoaDon.setText("Làm mới");
        btnLamMoiHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiHoaDonActionPerformed(evt);
            }
        });

        btnSuaHoaDon.setBackground(java.awt.Color.white);
        btnSuaHoaDon.setForeground(java.awt.Color.black);
        btnSuaHoaDon.setText("Sửa");
        btnSuaHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaHoaDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThemHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSuaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXoaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLamMoiHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemHoaDon)
                    .addComponent(btnSuaHoaDon)
                    .addComponent(btnXoaHoaDon)
                    .addComponent(btnLamMoiHoaDon))
                .addContainerGap())
        );

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnTableDanhSachHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpnRootLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(67, 67, 67))
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnTableDanhSachHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnQuanLyKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyKhachHangActionPerformed
        // TODO add your handling code here:
        if(btnQuanLyKhachHang.getText().equals("Quản lý khách hàng"))
        {
            
            JPanel node = new QuanLyKhachHang(txtSDTkhachHang.getText(),txtTenKhachHang.getText());
            jpnRoot.removeAll();
            jpnRoot.setLayout(new BorderLayout());
            jpnRoot.add(node);
            jpnRoot.validate();
            jpnRoot.repaint();
        }
        else
        {
            JPanel node = new QuanLyKhachHang(txtSDTkhachHang.getText(),txtTenKhachHang.getText());
            jpnRoot.removeAll();
            jpnRoot.setLayout(new BorderLayout());
            jpnRoot.add(node);
            jpnRoot.validate();
            jpnRoot.repaint();
        }
    }//GEN-LAST:event_btnQuanLyKhachHangActionPerformed

    private void btnThemHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemHoaDonActionPerformed
        // TODO add your handling code here:
        jpnHoaDonBan jpnhoaDon = new jpnHoaDonBan(jcbHinhThucThanhToan, txtMaHoaDon, txtMaNhanVien, txtNgayBan, txtSDTkhachHang, txtTenKhachHang,btnQuanLyKhachHang,jpnRoot);
        jpnhoaDon.ThemHoaDon(0);
    }//GEN-LAST:event_btnThemHoaDonActionPerformed

    private void btnLamMoiHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiHoaDonActionPerformed
        // TODO add your handling code here:
        controller.setDataToTable();
    }//GEN-LAST:event_btnLamMoiHoaDonActionPerformed

    private void txtSDTkhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTkhachHangActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtSDTkhachHangActionPerformed

    private void txtSDTkhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSDTkhachHangMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtSDTkhachHangMouseClicked

    private void txtSDTkhachHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSDTkhachHangMouseExited
        if(txtSDTkhachHang.getText().equals("")==false)
        {
            KhachHangDAO khachHangDAO = new KhachHangDAOImpl();
            List<KhachHang> listkhachHang = khachHangDAO.getList();
            boolean check = false;
            for(int i=0;i<listkhachHang.size();i++)
            {
                if(listkhachHang.get(i).getSoDienThoai().equals(txtSDTkhachHang.getText()))
                {
                    txtTenKhachHang.setText(listkhachHang.get(i).getTenKhachHang());
                    check = true;
                    break;
                }
            }
            
            if(check==true) 
            {
                btnQuanLyKhachHang.setText("Quản lý khách hàng");
                txtTenKhachHang.setEnabled(false);
                
            }
            else 
            {
                btnQuanLyKhachHang.setText("Thêm khách hàng");
                txtTenKhachHang.setEnabled(true);
            }
        }
    }//GEN-LAST:event_txtSDTkhachHangMouseExited
    
    private void btnTimKiemHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemHoaDonActionPerformed
        // TODO add your handling code here:
        List<HoaDonBan> listItem = controller.getListHoaDonBan();
        List<HoaDonBan> SearchListItem = new ArrayList<>();
        JTable table = controller.getTable();
        
        for(int i=0;i<listItem.size();i++)
        {
            if(txtTimKiemMaHoaDon.getText().length()>0&&listItem.get(i).getMaHoaDonBan().equalsIgnoreCase( txtTimKiemMaHoaDon.getText() )== false) continue;
            if(txtTimKiemMaNhanVien.getText().length()>0&&listItem.get(i).getNhan_vien_ban_hang().getMa_nhan_vien().equalsIgnoreCase( txtTimKiemMaNhanVien.getText() )== false) continue;
            
            if(txtTimKiemSDTkhachHang.getText().length()>0&&listItem.get(i).getKhach_mua_hang().getSoDienThoai().equalsIgnoreCase( txtTimKiemSDTkhachHang.getText() )== false) continue;
            
            
            
            Date date = new Date();
            try {
                date = new SimpleDateFormat("dd/MM/yyyy").parse(listItem.get(i).getNgayBan().toString());
            } catch (ParseException ex) {}
            
            if(txtTimKiemTuNgay.getText().length()>0)
            {
                Date dateTuNgay = new Date();
                try {
                    dateTuNgay = new SimpleDateFormat("dd/MM/yyyy").parse(txtTimKiemTuNgay.getText().toString());
                } catch (ParseException ex) {
                }
                if(date.getTime()<dateTuNgay.getTime())
                {
                    continue;
                }
            }
            
            if(txtTimKiemDenNgay.getText().length()>0)
            {
                Date dateDenNgay = new Date();
                try {
                    dateDenNgay = new SimpleDateFormat("dd/MM/yyyy").parse(txtTimKiemDenNgay.getText());
                } catch (ParseException ex) {
                }
                if(date.getTime()>dateDenNgay.getTime())
                {
                    continue;
                }
            }
            
            SearchListItem.add(listItem.get(i));
        }
        
        ClassTableModel ctm = new ClassTableModel();
        String [] CLOUMNS = controller.getColumnName();
        DefaultTableModel model = ctm.setTableHoaDonBan(SearchListItem, CLOUMNS );
        table.setModel(model);
        DefaultTableCellRenderer centerrender = new DefaultTableCellRenderer();

        centerrender.setHorizontalAlignment( JLabel.CENTER );
        
       table.getColumnModel().getColumn(0).setCellRenderer( centerrender );
        
            DefaultTableCellRenderer rightrender = new DefaultTableCellRenderer();
            rightrender.setHorizontalAlignment( JLabel.LEFT );
        table.getColumnModel().getColumn(1).setCellRenderer( rightrender );
        table.getColumnModel().getColumn(2).setCellRenderer( rightrender );
        table.getColumnModel().getColumn(3).setCellRenderer( rightrender );      
        table.getColumnModel().getColumn(4).setCellRenderer( rightrender );
        table.getColumnModel().getColumn(5).setCellRenderer( rightrender );
        table.getColumnModel().getColumn(6).setCellRenderer( rightrender );
        table.getColumnModel().getColumn(7).setCellRenderer( rightrender );
        
        JScrollPane scroll = new JScrollPane();
        scroll.getViewport().add(table);
        scroll.setPreferredSize(new Dimension(1350,330));
        
        jpnTableDanhSachHoaDon.removeAll();
        jpnTableDanhSachHoaDon.setLayout(new BorderLayout());
        jpnTableDanhSachHoaDon.add(scroll);
        jpnTableDanhSachHoaDon.validate();
        jpnTableDanhSachHoaDon.repaint();
    }//GEN-LAST:event_btnTimKiemHoaDonActionPerformed

    private void btnSuaHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaHoaDonActionPerformed
        // TODO add your handling code here:
        JTable table = controller.getTable();
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        int Row = controller.getRowSua();
        Row = table.convertColumnIndexToModel(Row);
        
        String sql_danhSachHoaDonBan = "DELETE FROM dbo.Danh_sach_hoa_don  " + "WHERE ma_hoa_don = ?";
        String sql_ChiTietHoaDonBan = "DELETE FROM dbo.ChiTietHoaDon " + "WHERE maHoaDon = ? ";
        String sql_Them = "INSERT INTO dbo.Danh_sach_hoa_don(ma_hoa_don,ma_nhan_vien,so_dien_thoai_khachHang,ngay_ban,hinh_thuc_thanh_toan)  " + " VALUES(?, ?,?,?,?) ";
        try (Connection c = DBConnect.getConnection();
        PreparedStatement ps_ChiTietHoaDonBan = c.prepareCall(sql_ChiTietHoaDonBan);
        PreparedStatement ps_DanhSachHoaDonBan = c.prepareCall(sql_danhSachHoaDonBan);        
        PreparedStatement ps_Them = c.prepareCall(sql_Them);)
        {
            if( ThemHoaDon(1) == 1)
            {
                ps_ChiTietHoaDonBan.setString(1, model.getValueAt(Row, 1).toString());
                ps_ChiTietHoaDonBan.executeUpdate();
                ps_DanhSachHoaDonBan.setString(1, model.getValueAt(Row, 1).toString());
                ps_DanhSachHoaDonBan.executeUpdate();
                ps_Them.setString(1, txtMaHoaDon.getText());
                ps_Them.setString(2, txtMaNhanVien.getText());
                ps_Them.setString(3, txtSDTkhachHang.getText());
                ps_Them.setString(4, txtNgayBan.getText());
                ps_Them.setString(5, jcbHinhThucThanhToan.getSelectedItem().toString());
                ps_Them.executeUpdate();
            }
            
        } catch (Exception ex) {System.out.println(ex.getMessage());}
    }//GEN-LAST:event_btnSuaHoaDonActionPerformed

    private void btnXoaHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaHoaDonActionPerformed
        // TODO add your handling code here:
        jpnHoaDonBan jpnhoaDon = new jpnHoaDonBan(jcbHinhThucThanhToan, txtMaHoaDon, txtMaNhanVien, txtNgayBan, txtSDTkhachHang, txtTenKhachHang,btnQuanLyKhachHang,jpnRoot);
        jpnhoaDon.XoaHoaDonBan();
        
    }//GEN-LAST:event_btnXoaHoaDonActionPerformed
    private void XoaHoaDonBan(){
        try 
        {
            String errors = "";
            if(txtMaHoaDon.getText().equals(""))
            {
                errors += "Mã hoá đơn chưa được nhập\n";
                txtMaHoaDon.setBackground(Color.red);
            }
            else txtMaHoaDon.setBackground(Color.WHITE);
           
            
            if(!errors.isEmpty())
            {
                JOptionPane.showMessageDialog(this, errors);
            }
            else
            {
                String sql_danhSachHoaDonBan = "DELETE FROM dbo.Danh_sach_hoa_don  " + "WHERE ma_hoa_don = ?";
                String sql_ChiTietHoaDonBan = "DELETE FROM dbo.ChiTietHoaDon " + "WHERE maHoaDon = ? ";
                try (Connection c = DBConnect.getConnection();
                PreparedStatement ps_DanhSachHoaDonBan = c.prepareCall(sql_danhSachHoaDonBan);
                PreparedStatement ps_ChiTietHoaDonBan = c.prepareCall(sql_ChiTietHoaDonBan);)
                {
                    ps_DanhSachHoaDonBan.setString(1, txtMaHoaDon.getText());
                    ps_ChiTietHoaDonBan.setString(1, txtMaHoaDon.getText());
                    HoaDonBanService hoaDonBanService = new HoaDonBanServiceImpl();
                    List<HoaDonBan> listHoaDon = hoaDonBanService.getList();
                    boolean check = false;
                    for(int i=0;i<listHoaDon.size();i++)
                    {
                        if(listHoaDon.get(i).getMaHoaDonBan().equals(txtMaHoaDon.getText()))
                        {
                            check = true;
                            break;
                        }
                    }
                    
                    if(check==true)
                    {
                        ps_ChiTietHoaDonBan.executeUpdate();
                        ps_DanhSachHoaDonBan.executeUpdate();
                        JOptionPane.showMessageDialog(this,"Đã XÓA thành công");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this,"Mã hóa đơn không có trong cơ sở dữ liệu");
                    }
                    
                } catch (Exception ex) {System.out.println(ex.getMessage());}
            }
        } 
        catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Erorr " + e.getMessage());
        }
    }
    private int ThemHoaDon(int joption ){
        try {
            String errors = "";
            if(txtMaHoaDon.getText().equals(""))
            {
                errors += "Mã hoá đơn chưa được nhập\n";
                txtMaHoaDon.setBackground(Color.red);
            }
            else txtMaHoaDon.setBackground(Color.WHITE);
           
            
            if(txtMaNhanVien.getText().equals(""))
            {
                errors+= "Mã nhân viên chưa được nhập\n";
                txtMaNhanVien.setBackground(Color.red);
            }
            else txtMaNhanVien.setBackground(Color.white);
            
            String Item = (String) jcbHinhThucThanhToan.getSelectedItem();
            if(Item.length()==1)
            {
                errors+= "Hình thức thanh toán chưa được chọn\n";
                jcbHinhThucThanhToan.setBackground(Color.red);
            }
            else jcbHinhThucThanhToan.setBackground(Color.white);
            
            if(txtNgayBan.getText().equals(""))
            {
                errors+= "Ngày bán chưa được nhập\n";
                txtNgayBan.setBackground(Color.red);
            }
            else txtNgayBan.setBackground(Color.white);
            
            if(txtSDTkhachHang.getText().equals(""))
            {
                errors+= "SDT Khách hàng chưa được nhập\n";
                txtSDTkhachHang.setBackground(Color.red);
            }
            else txtSDTkhachHang.setBackground(Color.white);
            
            if(txtTenKhachHang.getText().equals(""))
            {
                errors+= "Tên khách hàng chưa được nhập";
                txtTenKhachHang.setBackground(Color.red);
            }
            else txtTenKhachHang.setBackground(Color.white);
            
            if(!errors.isEmpty())
            {
                JOptionPane.showMessageDialog(this, errors);
            }
            else
            {
                
                String sql = "INSERT INTO dbo.Danh_sach_hoa_don (ma_hoa_don,ma_nhan_vien,so_dien_thoai_khachHang,ngay_ban,hinh_thuc_thanh_toan)" + " VALUES(?,?,?,?,?)";
                try (Connection c = DBConnect.getConnection();
                PreparedStatement ps = c.prepareCall(sql);)
                {
                    HoaDonDAO mtd = new HoaDonDAOImpl();
                    List<HoaDonBan> listHoaDonBan = mtd.getList();
                    
                    KhachHangDAO khachHangDAO = new KhachHangDAOImpl();
                    List<KhachHang> listkhachHang = khachHangDAO.getList();
                    
                    NhanVienDao nhanVienDAO = new NhanVienDAOImpl();
                    List<NhanVien> listnhanVien = nhanVienDAO.getListNhanVien();
                    
                    String error = "";
                    boolean checkHoaDon= true,checkManhanVien = false,checkSDTKhachHang = false;
                    for(int i=0;i<listHoaDonBan.size();i++)
                    {
                        if(listHoaDonBan.get(i).getMaHoaDonBan().equals(txtMaHoaDon.getText()))
                        {
                            error += "Mã hóa đơn đã có, hãy nhập mã khác\n";
                            checkHoaDon = false;
                            break;
                        }
                    }
                    
                    String nameNhanVien = "";
                    for(int i=0;i<listnhanVien.size();i++)
                    {
                        if(listnhanVien.get(i).getMa_nhan_vien().equals(txtMaNhanVien.getText()))
                        {
                            nameNhanVien = listnhanVien.get(i).getTen_nhan_vien();
                            checkManhanVien = true;
                            break;
                        }
                    }
                    
                    if(checkManhanVien==false) error+= "Mã nhân viên nhập sai\n";
                    
                    String maKhachHang = ""; 
                    for(int i=0;i<listkhachHang.size();i++)
                    {
                        if(listkhachHang.get(i).getSoDienThoai().equals(txtSDTkhachHang.getText()))
                        {
                            txtTenKhachHang.setText(listkhachHang.get(i).getTenKhachHang());
                            checkSDTKhachHang = true;
                            break;
                        }
                    }
                    
                    if(checkSDTKhachHang==false)
                    {
                        JOptionPane.showMessageDialog(this,"Khách hàng chưa có trong CSDL,cần được thêm");
                    }
                    else if(checkHoaDon==true&&checkManhanVien==true&&checkSDTKhachHang==true) 
                    {
                        Date date = new SimpleDateFormat("dd/MM/yyyy").parse(txtNgayBan.getText().toString());
                        SimpleDateFormat sdf = new SimpleDateFormat("MM-dd-yyyy");
                        
                        ps.setString(1, txtMaHoaDon.getText());
                        ps.setString(2, txtMaNhanVien.getText());
                        ps.setString(3, txtSDTkhachHang.getText() );
                        ps.setString(4, sdf.format(date) );
                        ps.setString(5, jcbHinhThucThanhToan.getSelectedItem().toString() );
                        ps.executeUpdate();
                        if(joption==0) 
                        {
                            JOptionPane.showMessageDialog(this,"Đã THÊM Hóa đơn thành công");
                            
                            JPanel node = new QuanLyChiTietHoaDon("",jcbHinhThucThanhToan.getSelectedItem().toString(),txtMaHoaDon.getText(),txtNgayBan.getText(),nameNhanVien,txtSDTkhachHang.getText(),txtTenKhachHang.getText());
                            jpnRoot.removeAll();
                            jpnRoot.setLayout(new BorderLayout());
                            jpnRoot.add(node);
                            jpnRoot.validate();
                            jpnRoot.repaint();
                        }
                        else JOptionPane.showMessageDialog(this,"Đã SỬA thành công");
                        return 1;
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, error);
                        return 0;
                    }
                    
                } catch (Exception ex) {System.out.println(ex.getMessage());}
            }
        } 
        catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Erorr " + e.getMessage());
        }
        return 0;
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoiHoaDon;
    private javax.swing.JButton btnQuanLyKhachHang;
    private javax.swing.JButton btnSuaHoaDon;
    private javax.swing.JButton btnThemHoaDon;
    private javax.swing.JButton btnTimKiemHoaDon;
    private javax.swing.JButton btnXoaHoaDon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JComboBox<String> jcbHinhThucThanhToan;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JPanel jpnTableDanhSachHoaDon;
    private javax.swing.JTextField txtMaHoaDon;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtNgayBan;
    private javax.swing.JTextField txtSDTkhachHang;
    private javax.swing.JTextField txtTenKhachHang;
    private javax.swing.JTextField txtTimKiemDenNgay;
    private javax.swing.JTextField txtTimKiemMaHoaDon;
    private javax.swing.JTextField txtTimKiemMaNhanVien;
    private javax.swing.JTextField txtTimKiemSDTkhachHang;
    private javax.swing.JTextField txtTimKiemTuNgay;
    // End of variables declaration//GEN-END:variables
}
