/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.view;
import java.util.*;
import com.mycompany.controller.ChuyenManHinhController;
import com.mycompany.DanhMucBean.DanhMucBean;
import java.awt.Color;
/**
 *
 * @author Admin
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setTitle("Quản Lý Điện Thoại");
        jpnQuanLySanPham.setBackground(Color.RED);
        jlbQuanLySanPham.setForeground(Color.WHITE);
        jpnQuanLyNhanVien.setBackground(Color.RED);
        jlbQuanLyNhanVien.setForeground(Color.WHITE);
        jpnQuanLyHoaDonBan.setBackground(Color.RED);
        jlbQuanLyHoaDonBan.setForeground(Color.WHITE);
        jpnQuanLyHoaDonNhap.setBackground(Color.RED);
        jlbQuanLyHoaDonNhap.setForeground(Color.WHITE);
        ChuyenManHinhController controller = new ChuyenManHinhController(jpnView);
        controller.setView(jpnQuanLySanPham, jlbQuanLySanPham);
        List<DanhMucBean> listItem = new ArrayList<>();
        listItem.add(new DanhMucBean("QuanLySanPham",jpnQuanLySanPham,jlbQuanLySanPham));
        listItem.add(new DanhMucBean("QuanLyNhanVien",jpnQuanLyNhanVien,jlbQuanLyNhanVien));
        listItem.add(new DanhMucBean("QuanLyHoaDonBan",jpnQuanLyHoaDonBan,jlbQuanLyHoaDonBan));
        listItem.add(new DanhMucBean("QuanLyHoaDonNhap",jpnQuanLyHoaDonNhap,jlbQuanLyHoaDonNhap));
        controller.setEvent(listItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jpnMenu = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpnQuanLySanPham = new javax.swing.JPanel();
        jlbQuanLySanPham = new javax.swing.JLabel();
        jpnQuanLyNhanVien = new javax.swing.JPanel();
        jlbQuanLyNhanVien = new javax.swing.JLabel();
        jpnQuanLyHoaDonBan = new javax.swing.JPanel();
        jlbQuanLyHoaDonBan = new javax.swing.JLabel();
        jpnQuanLyHoaDonNhap = new javax.swing.JPanel();
        jlbQuanLyHoaDonNhap = new javax.swing.JLabel();
        jpnView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnRoot.setBackground(java.awt.Color.red);

        jpnMenu.setBackground(java.awt.Color.red);

        jPanel3.setBackground(java.awt.Color.yellow);

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.red);
        jLabel1.setText("Quản Lý Cửa Hàng Máy Tính");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jpnQuanLySanPham.setBackground(java.awt.Color.red);

        jlbQuanLySanPham.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jlbQuanLySanPham.setForeground(java.awt.Color.white);
        jlbQuanLySanPham.setText("Quản Lý Sản Phẩm ");

        javax.swing.GroupLayout jpnQuanLySanPhamLayout = new javax.swing.GroupLayout(jpnQuanLySanPham);
        jpnQuanLySanPham.setLayout(jpnQuanLySanPhamLayout);
        jpnQuanLySanPhamLayout.setHorizontalGroup(
            jpnQuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQuanLySanPhamLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jlbQuanLySanPham)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jpnQuanLySanPhamLayout.setVerticalGroup(
            jpnQuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnQuanLySanPhamLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbQuanLySanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpnQuanLyNhanVien.setBackground(java.awt.Color.red);

        jlbQuanLyNhanVien.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jlbQuanLyNhanVien.setText("Quản Lý Nhân Viên");

        javax.swing.GroupLayout jpnQuanLyNhanVienLayout = new javax.swing.GroupLayout(jpnQuanLyNhanVien);
        jpnQuanLyNhanVien.setLayout(jpnQuanLyNhanVienLayout);
        jpnQuanLyNhanVienLayout.setHorizontalGroup(
            jpnQuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQuanLyNhanVienLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jlbQuanLyNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jpnQuanLyNhanVienLayout.setVerticalGroup(
            jpnQuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQuanLyNhanVienLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jlbQuanLyNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnQuanLyHoaDonBan.setBackground(java.awt.Color.red);

        jlbQuanLyHoaDonBan.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jlbQuanLyHoaDonBan.setText("Quản Lý Hóa Đơn Bán ");

        javax.swing.GroupLayout jpnQuanLyHoaDonBanLayout = new javax.swing.GroupLayout(jpnQuanLyHoaDonBan);
        jpnQuanLyHoaDonBan.setLayout(jpnQuanLyHoaDonBanLayout);
        jpnQuanLyHoaDonBanLayout.setHorizontalGroup(
            jpnQuanLyHoaDonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnQuanLyHoaDonBanLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jlbQuanLyHoaDonBan)
                .addGap(63, 63, 63))
        );
        jpnQuanLyHoaDonBanLayout.setVerticalGroup(
            jpnQuanLyHoaDonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQuanLyHoaDonBanLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlbQuanLyHoaDonBan)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jpnQuanLyHoaDonNhap.setBackground(java.awt.Color.red);

        jlbQuanLyHoaDonNhap.setBackground(java.awt.Color.red);
        jlbQuanLyHoaDonNhap.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jlbQuanLyHoaDonNhap.setForeground(java.awt.Color.white);
        jlbQuanLyHoaDonNhap.setText("Quản Lý Hóa Đơn Nhập");

        javax.swing.GroupLayout jpnQuanLyHoaDonNhapLayout = new javax.swing.GroupLayout(jpnQuanLyHoaDonNhap);
        jpnQuanLyHoaDonNhap.setLayout(jpnQuanLyHoaDonNhapLayout);
        jpnQuanLyHoaDonNhapLayout.setHorizontalGroup(
            jpnQuanLyHoaDonNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnQuanLyHoaDonNhapLayout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jlbQuanLyHoaDonNhap)
                .addGap(50, 50, 50))
        );
        jpnQuanLyHoaDonNhapLayout.setVerticalGroup(
            jpnQuanLyHoaDonNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQuanLyHoaDonNhapLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbQuanLyHoaDonNhap)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnMenuLayout = new javax.swing.GroupLayout(jpnMenu);
        jpnMenu.setLayout(jpnMenuLayout);
        jpnMenuLayout.setHorizontalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnQuanLyNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnQuanLyHoaDonNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnQuanLySanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnQuanLyHoaDonBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnMenuLayout.setVerticalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jpnQuanLySanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jpnQuanLyNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jpnQuanLyHoaDonNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jpnQuanLyHoaDonBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jpnView.setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnRootLayout.createSequentialGroup()
                .addComponent(jpnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jlbQuanLyHoaDonBan;
    private javax.swing.JLabel jlbQuanLyHoaDonNhap;
    private javax.swing.JLabel jlbQuanLyNhanVien;
    private javax.swing.JLabel jlbQuanLySanPham;
    private javax.swing.JPanel jpnMenu;
    private javax.swing.JPanel jpnQuanLyHoaDonBan;
    private javax.swing.JPanel jpnQuanLyHoaDonNhap;
    private javax.swing.JPanel jpnQuanLyNhanVien;
    private javax.swing.JPanel jpnQuanLySanPham;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JPanel jpnView;
    // End of variables declaration//GEN-END:variables
}
