/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.view;
import com.mycompany.dao.DBConnect;
import com.mycompany.model.MayTinh;
import java.util.List;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import com.mycompany.dao.MayTinhDAOImpl;
import com.mycompany.dao.MayTinhDAO;
import com.mycompany.controller.QuanLyMayTinhController;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import com.mycompany.utility.ClassTableModel;
import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableCellRenderer;
/**
 *
 * @author Admin
 */
public class QuanLySanPham extends javax.swing.JPanel {

    /**
     * Creates new form QuanLySanPham
     */
    public QuanLySanPham(JComboBox<String> jcbThoiGianBaoHanh, JTextField txtGiaBan, JTextField txtMaMayTinh, JTextField txtSoLuong, JTextField txtTenMayTinh, JTextField txtXuatXu) {
        initComponents();
        this.jcbThoiGianBaoHanh = jcbThoiGianBaoHanh;
        this.txtGiaBan = txtGiaBan;
        this.txtMaMayTinh = txtMaMayTinh;
        this.txtSoLuong = txtSoLuong;
        this.txtTenMayTinh = txtTenMayTinh;
        this.txtXuatXu = txtXuatXu;
    }

    
    QuanLyMayTinhController controller;
    public QuanLySanPham() {
        initComponents();
        controller = new QuanLyMayTinhController(txtMaMayTinh,txtTenMayTinh,jcbThoiGianBaoHanh,txtXuatXu,txtGiaBan,txtSoLuong,jpnTableQLSP);
        controller.setDataToTable();
        jpnChucNangSanPham.validate();
        jpnChucNangSanPham.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTenMayTinh = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMaMayTinh = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jcbThoiGianBaoHanh = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtXuatXu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtGiaBan = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtTimKiemTMT = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTimKiemMMT = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTimKiemSoLuongDen = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTimKiemSoLuongTu = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTimKiemGiaTu = new javax.swing.JTextField();
        btnTimKiemSanPham = new javax.swing.JButton();
        jlbTimKiemSoLuong = new javax.swing.JLabel();
        txtTimKiemXuatXu = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtTimKiemGiaDen = new javax.swing.JTextField();
        jpnTableQLSP = new javax.swing.JPanel();
        jpnChucNangSanPham = new javax.swing.JPanel();
        btnLamMoi = new javax.swing.JButton();
        btnXoaSanPham = new javax.swing.JButton();
        btnSuaSanPham = new javax.swing.JButton();
        btnThemSanPham = new javax.swing.JButton();

        jPanel3.setBackground(java.awt.Color.white);
        jPanel3.setForeground(java.awt.Color.black);

        jPanel1.setBackground(java.awt.Color.yellow);
        jPanel1.setForeground(java.awt.Color.white);

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.red);
        jLabel1.setText("Quản Lý Sản Phẩm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(462, 462, 462)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBackground(java.awt.Color.white);
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Sản Phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12), java.awt.Color.black)); // NOI18N
        jPanel2.setForeground(java.awt.Color.black);

        jLabel2.setBackground(java.awt.Color.white);
        jLabel2.setForeground(java.awt.Color.black);
        jLabel2.setText("Tên máy tính");

        txtTenMayTinh.setBackground(java.awt.Color.white);
        txtTenMayTinh.setForeground(java.awt.Color.black);

        jLabel3.setBackground(java.awt.Color.white);
        jLabel3.setForeground(java.awt.Color.black);
        jLabel3.setText("Mã máy tính");

        txtMaMayTinh.setBackground(java.awt.Color.white);
        txtMaMayTinh.setForeground(java.awt.Color.black);

        jLabel4.setBackground(java.awt.Color.white);
        jLabel4.setForeground(java.awt.Color.black);
        jLabel4.setText("Thời gian bảo hành");

        jcbThoiGianBaoHanh.setBackground(java.awt.Color.white);
        jcbThoiGianBaoHanh.setForeground(java.awt.Color.black);
        jcbThoiGianBaoHanh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "6 tháng", "12 tháng", "24 tháng", "48 tháng" }));

        jLabel5.setBackground(java.awt.Color.white);
        jLabel5.setForeground(java.awt.Color.black);
        jLabel5.setText("Xuất xứ");

        txtXuatXu.setBackground(java.awt.Color.white);
        txtXuatXu.setForeground(java.awt.Color.black);

        jLabel6.setBackground(java.awt.Color.white);
        jLabel6.setForeground(java.awt.Color.black);
        jLabel6.setText("Giá bán");

        txtSoLuong.setBackground(java.awt.Color.white);
        txtSoLuong.setForeground(java.awt.Color.black);

        jLabel7.setBackground(java.awt.Color.white);
        jLabel7.setForeground(java.awt.Color.black);
        jLabel7.setText("Số lượng");

        txtGiaBan.setBackground(java.awt.Color.white);
        txtGiaBan.setForeground(java.awt.Color.black);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaMayTinh)
                    .addComponent(jcbThoiGianBaoHanh, javax.swing.GroupLayout.Alignment.TRAILING, 0, 180, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenMayTinh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaBan, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(txtXuatXu)
                    .addComponent(txtSoLuong))
                .addGap(48, 48, 48))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaMayTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtXuatXu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenMayTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jcbThoiGianBaoHanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        jPanel4.setBackground(java.awt.Color.white);
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm Kiếm Sản Phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12), java.awt.Color.black)); // NOI18N
        jPanel4.setForeground(java.awt.Color.black);

        jLabel8.setBackground(java.awt.Color.white);
        jLabel8.setForeground(java.awt.Color.black);
        jLabel8.setText("Xuất xứ");

        txtTimKiemTMT.setBackground(java.awt.Color.white);
        txtTimKiemTMT.setForeground(java.awt.Color.black);

        jLabel9.setBackground(java.awt.Color.white);
        jLabel9.setForeground(java.awt.Color.black);
        jLabel9.setText("Mã máy tính");

        txtTimKiemMMT.setBackground(java.awt.Color.white);
        txtTimKiemMMT.setForeground(java.awt.Color.black);

        jLabel10.setBackground(java.awt.Color.white);
        jLabel10.setForeground(java.awt.Color.black);
        jLabel10.setText("Tên máy tính");

        txtTimKiemSoLuongDen.setBackground(java.awt.Color.white);
        txtTimKiemSoLuongDen.setForeground(java.awt.Color.black);

        jLabel11.setBackground(java.awt.Color.white);
        jLabel11.setForeground(java.awt.Color.black);
        jLabel11.setText("Đến");

        txtTimKiemSoLuongTu.setBackground(java.awt.Color.white);
        txtTimKiemSoLuongTu.setForeground(java.awt.Color.black);

        jLabel12.setBackground(java.awt.Color.white);
        jLabel12.setForeground(java.awt.Color.black);
        jLabel12.setText("Giá từ");

        txtTimKiemGiaTu.setBackground(java.awt.Color.white);
        txtTimKiemGiaTu.setForeground(java.awt.Color.black);

        btnTimKiemSanPham.setBackground(java.awt.Color.white);
        btnTimKiemSanPham.setForeground(java.awt.Color.black);
        btnTimKiemSanPham.setText("Tìm Kiếm");
        btnTimKiemSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemSanPhamActionPerformed(evt);
            }
        });

        jlbTimKiemSoLuong.setBackground(java.awt.Color.white);
        jlbTimKiemSoLuong.setForeground(java.awt.Color.black);
        jlbTimKiemSoLuong.setText("Số lượng từ");

        txtTimKiemXuatXu.setBackground(java.awt.Color.white);
        txtTimKiemXuatXu.setForeground(java.awt.Color.black);

        jLabel13.setBackground(java.awt.Color.white);
        jLabel13.setForeground(java.awt.Color.black);
        jLabel13.setText("Đến");

        txtTimKiemGiaDen.setBackground(java.awt.Color.white);
        txtTimKiemGiaDen.setForeground(java.awt.Color.black);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbTimKiemSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTimKiemMMT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(txtTimKiemTMT, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTimKiemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTimKiemGiaTu, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTimKiemXuatXu, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTimKiemSoLuongTu, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(txtTimKiemSoLuongDen, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTimKiemGiaDen, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiemMMT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiemTMT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiemXuatXu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTimKiemSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiemSoLuongTu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiemSoLuongDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiemGiaTu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiemGiaDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnTableQLSP.setBackground(java.awt.Color.white);
        jpnTableQLSP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12), java.awt.Color.black)); // NOI18N
        jpnTableQLSP.setForeground(java.awt.Color.black);

        javax.swing.GroupLayout jpnTableQLSPLayout = new javax.swing.GroupLayout(jpnTableQLSP);
        jpnTableQLSP.setLayout(jpnTableQLSPLayout);
        jpnTableQLSPLayout.setHorizontalGroup(
            jpnTableQLSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        jpnTableQLSPLayout.setVerticalGroup(
            jpnTableQLSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );

        jpnChucNangSanPham.setBackground(java.awt.Color.white);
        jpnChucNangSanPham.setForeground(java.awt.Color.black);

        btnLamMoi.setBackground(java.awt.Color.white);
        btnLamMoi.setForeground(java.awt.Color.black);
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnXoaSanPham.setBackground(java.awt.Color.white);
        btnXoaSanPham.setForeground(java.awt.Color.black);
        btnXoaSanPham.setText("Xóa");
        btnXoaSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSanPhamActionPerformed(evt);
            }
        });

        btnSuaSanPham.setBackground(java.awt.Color.white);
        btnSuaSanPham.setForeground(java.awt.Color.black);
        btnSuaSanPham.setText("Sửa");
        btnSuaSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaSanPhamActionPerformed(evt);
            }
        });

        btnThemSanPham.setBackground(java.awt.Color.white);
        btnThemSanPham.setForeground(java.awt.Color.black);
        btnThemSanPham.setText("Thêm ");
        btnThemSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSanPhamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnChucNangSanPhamLayout = new javax.swing.GroupLayout(jpnChucNangSanPham);
        jpnChucNangSanPham.setLayout(jpnChucNangSanPhamLayout);
        jpnChucNangSanPhamLayout.setHorizontalGroup(
            jpnChucNangSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnChucNangSanPhamLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btnThemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addComponent(btnSuaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160)
                .addComponent(btnXoaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160)
                .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        jpnChucNangSanPhamLayout.setVerticalGroup(
            jpnChucNangSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnChucNangSanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnChucNangSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoaSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSuaSanPham)
                    .addComponent(btnThemSanPham))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpnChucNangSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnTableQLSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnTableQLSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnChucNangSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnThemSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSanPhamActionPerformed
        // TODO add your handling code here:
//        System.out.println(txtMaMayTinh.getText() + " " + txtMaMayTinh.getText().length());
        QuanLySanPham qlsp = new QuanLySanPham(jcbThoiGianBaoHanh, txtGiaBan, txtMaMayTinh, txtSoLuong, txtTenMayTinh, txtXuatXu);
        qlsp.ThemSanPham(0);
    }//GEN-LAST:event_btnThemSanPhamActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        controller.setDataToTable();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnSuaSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaSanPhamActionPerformed
        // TODO add your handling code here:
        JTable table = controller.getTable();
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        int Row = controller.getRowSua();
        Row = table.convertColumnIndexToModel(Row);
        
        String sql_XOA = "DELETE FROM dbo.SanPham  " + "WHERE ma_may_tinh = ?";
        String sql_Them = "INSERT INTO dbo.SanPham(ma_may_tinh,ten_may_tinh,xuat_xu,thoi_gian_bao_hanh,so_luong,gia_ban)    " + " VALUES(?, ?, ?, ? , ? ,  ? ) ";
        try (Connection c = DBConnect.getConnection();
        PreparedStatement ps_Xoa = c.prepareCall(sql_XOA);
        PreparedStatement ps_Them = c.prepareCall(sql_Them);)
        {
            ps_Xoa.setString(1, model.getValueAt(Row, 1).toString());
            if( ThemSanPham(1) == 1)
            {
                ps_Xoa.executeUpdate();
                ps_Them.setString(1, txtMaMayTinh.getText());
                ps_Them.setString(2, txtTenMayTinh.getText());
                ps_Them.setString(3,txtXuatXu.getText());
                ps_Them.setString(4, jcbThoiGianBaoHanh.getSelectedItem().toString());
                ps_Them.setInt(5, Integer.valueOf(txtSoLuong.getText()) );
                ps_Them.setInt(6, Integer.valueOf(txtGiaBan.getText()) );
                ps_Them.executeUpdate();
            }
            
        } catch (Exception ex) {System.out.println(ex.getMessage());}
    }//GEN-LAST:event_btnSuaSanPhamActionPerformed

    private void btnXoaSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaSanPhamActionPerformed
        // TODO add your handling code here:
        QuanLySanPham qlsp = new QuanLySanPham(jcbThoiGianBaoHanh, txtGiaBan, txtMaMayTinh, txtSoLuong, txtTenMayTinh, txtXuatXu);
        qlsp.XoaSanPham();
    }//GEN-LAST:event_btnXoaSanPhamActionPerformed

    private void btnTimKiemSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemSanPhamActionPerformed
        // TODO add your handling code here:
        List<MayTinh> listItem = controller.getListMayTinh();
        List<MayTinh> SearchListItem = new ArrayList<>();
        JTable table = controller.getTable();
        
        for(int i=0;i<listItem.size();i++)
        {
            if(txtTimKiemXuatXu.getText().length()>0&&listItem.get(i).getXuat_xu().equalsIgnoreCase( txtTimKiemXuatXu.getText() )== false) continue;
            if(txtTimKiemMMT.getText().length()>0&&listItem.get(i).getMa_may_tinh().equalsIgnoreCase( txtTimKiemMMT.getText() )== false) continue;
            if(txtTimKiemTMT.getText().length()>0&&listItem.get(i).getTen_may_tinh().equalsIgnoreCase( txtTimKiemTMT.getText() )== false) continue;
            if(txtTimKiemGiaTu.getText().length()>0 )
            {
                int Gia_tu = Integer.valueOf(txtTimKiemGiaTu.getText());
                if(listItem.get(i).getGia_ban()<Gia_tu ) continue;
            }
            
            if(txtTimKiemGiaDen.getText().length()>0 )
            {
                int Gia_den = Integer.valueOf(txtTimKiemGiaDen.getText());
                if(listItem.get(i).getGia_ban()>Gia_den ) continue;
            }
            
            
            
            if(txtTimKiemSoLuongTu.getText().length()>0 )
            {
                int SO_LUONG_TU = Integer.valueOf(txtTimKiemSoLuongTu.getText());
                if(listItem.get(i).getSo_luong() < SO_LUONG_TU ) continue;
            }
            
            if(txtTimKiemSoLuongDen.getText().length()>0 )
            {
                int SO_LUONG_DEN = Integer.valueOf(txtTimKiemSoLuongDen.getText());
                if(listItem.get(i).getSo_luong()> SO_LUONG_DEN ) continue;
            }
            SearchListItem.add(listItem.get(i));
        }
        
        ClassTableModel ctm = new ClassTableModel();
        String [] CLOUMNS = controller.getColumnName();
        DefaultTableModel model = ctm.setTableMayTinh(SearchListItem, CLOUMNS );
        table.setModel(model);
        DefaultTableCellRenderer centerrender = new DefaultTableCellRenderer();

        centerrender.setHorizontalAlignment( JLabel.CENTER );
        
        table.getColumnModel().getColumn(0).setCellRenderer( centerrender );
        
        DefaultTableCellRenderer rightrender = new DefaultTableCellRenderer();
        rightrender.setHorizontalAlignment( JLabel.LEFT );
        table.getColumnModel().getColumn(1).setCellRenderer( rightrender );
        table.getColumnModel().getColumn(2).setCellRenderer( rightrender );
        table.getColumnModel().getColumn(3).setCellRenderer( rightrender );
        table.getColumnModel().getColumn(4).setCellRenderer( rightrender );
        table.getColumnModel().getColumn(5).setCellRenderer( rightrender );
        table.getColumnModel().getColumn(6).setCellRenderer( rightrender );
        
        JScrollPane scroll = new JScrollPane();
        scroll.getViewport().add(table);
        scroll.setPreferredSize(new Dimension(1350,330));
        jpnTableQLSP.removeAll();
        jpnTableQLSP.setLayout(new BorderLayout());
        jpnTableQLSP.add(scroll);
        jpnTableQLSP.validate();
        jpnTableQLSP.repaint();
        
    }//GEN-LAST:event_btnTimKiemSanPhamActionPerformed

    private void XoaSanPham(){
        try {
            String errors = "";
            if(txtMaMayTinh.getText().equals(""))
            {
                errors += "Mã máy tính chưa được nhập\n";
                txtMaMayTinh.setBackground(Color.red);
            }
            else    txtMaMayTinh.setBackground(Color.WHITE);
           
            
            if(txtTenMayTinh.getText().equals(""))
            {
                errors+= "Tên máy tính chưa được nhập\n";
                txtTenMayTinh.setBackground(Color.red);
            }
            else txtTenMayTinh.setBackground(Color.white);
            
            String Item = (String) jcbThoiGianBaoHanh.getSelectedItem();
            if(Item.length()==1)
            {
                errors+= "Thời gian bảo hành chưa được nhập\n";
                jcbThoiGianBaoHanh.setBackground(Color.red);
            }
            else jcbThoiGianBaoHanh.setBackground(Color.white);
            
            if(txtXuatXu.getText().equals(""))
            {
                errors+= "Xuất xứ chưa được nhập\n";
                txtXuatXu.setBackground(Color.red);
            }
            else txtXuatXu.setBackground(Color.white);
            
            if(txtGiaBan.getText().equals(""))
            {
                errors+= "Giá bán chưa được nhập\n";
                txtGiaBan.setBackground(Color.red);
            }
            else txtGiaBan.setBackground(Color.white);
            
            if(txtSoLuong.getText().equals(""))
            {
                errors+= "Số lượng chưa được nhập";
                txtSoLuong.setBackground(Color.red);
            }
            else txtSoLuong.setBackground(Color.white);
            
            if(!errors.isEmpty())
            {
                JOptionPane.showMessageDialog(this, errors);
            }
            else
            {
                String sql = "DELETE FROM dbo.SanPham  " + "WHERE ma_may_tinh = ?";
                try (Connection c = DBConnect.getConnection();
                PreparedStatement ps = c.prepareCall(sql);)
                {
                    ps.setString(1, txtMaMayTinh.getText());
                    
                    MayTinhDAO mtd = new MayTinhDAOImpl();
                    List<MayTinh> list_may_tinh = mtd.getList();
                    boolean check = false;
                    for(int i=0;i<list_may_tinh.size();i++)
                    {
                        if(list_may_tinh.get(i).getMa_may_tinh().equals(txtMaMayTinh.getText()))
                        {
                            check = true;
                            break;
                        }
                    }
                    
                    if(check==true)
                    {
                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(this,"Đã XÓA thành công");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this,"Mã máy tính không có trong cơ sở dữ liệu");
                    }
                    
                } catch (Exception ex) {System.out.println(ex.getMessage());}
            }
        } 
        catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Erorr " + e.getMessage());
        }
    }
    private int ThemSanPham(int joption ){
        try {
            //System.out.println(txtMaMayTinh.getText() + " " + txtMaMayTinh.getText().length());
            String errors = "";
            if(txtMaMayTinh.getText().equals(""))
            {
                errors += "Mã máy tính chưa được nhập\n";
                txtMaMayTinh.setBackground(Color.red);
            }
            else    txtMaMayTinh.setBackground(Color.WHITE);
           
            
            if(txtTenMayTinh.getText().equals(""))
            {
                errors+= "Tên máy tính chưa được nhập\n";
                txtTenMayTinh.setBackground(Color.red);
            }
            else txtTenMayTinh.setBackground(Color.white);
            
            String Item = (String) jcbThoiGianBaoHanh.getSelectedItem();
            if(Item.length()==1)
            {
                errors+= "Thời gian bảo hành chưa được nhập\n";
                jcbThoiGianBaoHanh.setBackground(Color.red);
            }
            else jcbThoiGianBaoHanh.setBackground(Color.white);
            
            if(txtXuatXu.getText().equals(""))
            {
                errors+= "Xuất xứ chưa được nhập\n";
                txtXuatXu.setBackground(Color.red);
            }
            else txtXuatXu.setBackground(Color.white);
            
            if(txtGiaBan.getText().equals(""))
            {
                errors+= "Giá bán chưa được nhập\n";
                txtGiaBan.setBackground(Color.red);
            }
            else txtGiaBan.setBackground(Color.white);
            
            if(txtSoLuong.getText().equals(""))
            {
                errors+= "Số lượng chưa được nhập";
                txtSoLuong.setBackground(Color.red);
            }
            else txtSoLuong.setBackground(Color.white);
            
            if(!errors.isEmpty())
            {
                JOptionPane.showMessageDialog(this, errors);
            }
            else
            {
                if(joption==0)
                {
                    String sql = "INSERT INTO dbo.SanPham(ma_may_tinh,ten_may_tinh,xuat_xu,thoi_gian_bao_hanh,so_luong,gia_ban)    " + " VALUES(?, ?, ?, ? , ? ,  ? ) ";
                    try (Connection c = DBConnect.getConnection();
                    PreparedStatement ps = c.prepareCall(sql);)
                    {
                        ps.setString(1, txtMaMayTinh.getText());
                        ps.setString(2, txtTenMayTinh.getText());
                        ps.setString(3,txtXuatXu.getText());
                        ps.setString(4, jcbThoiGianBaoHanh.getSelectedItem().toString());
                        ps.setInt(5, Integer.valueOf(txtSoLuong.getText()) );
                        ps.setInt(6, Integer.valueOf( txtGiaBan.getText() ) );

                        MayTinhDAO mtd = new MayTinhDAOImpl();
                        List<MayTinh> list_may_tinh = mtd.getList();
                        boolean check = true;
                        for(int i=0;i<list_may_tinh.size();i++)
                        {
                            if(list_may_tinh.get(i).getMa_may_tinh().equals(txtMaMayTinh.getText()))
                            {
                                check = false;
                                break;
                            }
                        }

                        if(check==true) 
                        {
                            ps.executeUpdate();
                            if(joption==0) 
                            {
                                JOptionPane.showMessageDialog(this,"Đã THÊM thành công");
                                return 0;
                            }
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(this, "Mã máy tính đã có, hãy nhập mã khác");
                            return 0;
                        }

                    } catch (Exception ex) {System.out.println(ex.getMessage());}
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Đã SỬA thành công");
                    return 1;
                }
            } 
        }
        catch (Exception e) {  JOptionPane.showMessageDialog(this, "Erorr " + e.getMessage()); }
        return 0;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSuaSanPham;
    private javax.swing.JButton btnThemSanPham;
    private javax.swing.JButton btnTimKiemSanPham;
    private javax.swing.JButton btnXoaSanPham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JComboBox<String> jcbThoiGianBaoHanh;
    private javax.swing.JLabel jlbTimKiemSoLuong;
    private javax.swing.JPanel jpnChucNangSanPham;
    private javax.swing.JPanel jpnTableQLSP;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtMaMayTinh;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenMayTinh;
    private javax.swing.JTextField txtTimKiemGiaDen;
    private javax.swing.JTextField txtTimKiemGiaTu;
    private javax.swing.JTextField txtTimKiemMMT;
    private javax.swing.JTextField txtTimKiemSoLuongDen;
    private javax.swing.JTextField txtTimKiemSoLuongTu;
    private javax.swing.JTextField txtTimKiemTMT;
    private javax.swing.JTextField txtTimKiemXuatXu;
    private javax.swing.JTextField txtXuatXu;
    // End of variables declaration//GEN-END:variables
}
