/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.view;

import com.mycompany.controller.QuanLyKhachHangController;
import com.mycompany.controller.QuanLyNhaCungCapController;
import com.mycompany.dao.ChiTietHoaDonDAO;
import com.mycompany.dao.ChiTietHoaDonNhapDAO;
import com.mycompany.dao.ChiTietHoaDonNhapImpl;
import com.mycompany.dao.ChucVuDAO;
import com.mycompany.dao.ChucVuDAOImpl;
import com.mycompany.dao.DBConnect;
import com.mycompany.dao.HoaDonNhapDAO;
import com.mycompany.dao.HoaDonNhapDAOImpl;
import com.mycompany.dao.KhachHangDAO;
import com.mycompany.dao.KhachHangDAOImpl;
import com.mycompany.dao.NhaCungCapDAO;
import com.mycompany.dao.NhaCungCapDAOImpl;
import com.mycompany.model.ChiTietHoaDonNhap;
import com.mycompany.model.ChucVu;
import com.mycompany.model.HoaDonNhap;
import com.mycompany.model.KhachHang;
import com.mycompany.model.NhaCungCap;
import com.mycompany.model.NhanVien;
import com.mycompany.utility.ClassTableModel;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class QuanLyNhaCungCap extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyChiTietHoaDonNhap
     */
    
    QuanLyNhaCungCapController controller;
    public QuanLyNhaCungCap() {
        initComponents();
    }
    
    QuanLyNhaCungCap(String txtMaNhaCungCap,String txtTenNhaCungCap,String txtSdtNhaCungCap,String txtDiaChi,String txtEmail) {
        initComponents();
        this.txtMaNhaCungCap.setText(txtMaNhaCungCap);
        this.txtTenNhaCungCap.setText(txtTenNhaCungCap);
        this.txtSDTnhaCungCap.setText(txtSdtNhaCungCap);
        this.txtDiaChi.setText(txtDiaChi);
        this.txtEmail.setText(txtEmail);
        controller = new QuanLyNhaCungCapController(this.txtMaNhaCungCap, this.txtTenNhaCungCap, this.txtSDTnhaCungCap, this.txtDiaChi, this.txtEmail, jpnTableNhaCungCap);
        controller.setDataToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMaNhaCungCap = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSDTnhaCungCap = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTenNhaCungCap = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtTimKiemDiaChiNhaCungCap = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTimKiemSDTNhaCungCap = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTimKiemEmailNhaCungCap = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTimKiemMaNhaCungCap = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTimKiemTenNhaCungCap = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jpnTableNhaCungCap = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnThoat = new javax.swing.JButton();
        btnThemNhaCungCap = new javax.swing.JButton();
        btnSuaNhaCungCap = new javax.swing.JButton();
        btnXoaNhaCungCap = new javax.swing.JButton();
        btnLamMoiNhaCungCap = new javax.swing.JButton();

        jpnRoot.setBackground(java.awt.Color.white);

        jPanel2.setBackground(java.awt.Color.orange);

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel1.setForeground(java.awt.Color.black);
        jLabel1.setText("Quản lý nhà cung cấp");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(java.awt.Color.white);
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin nhà cung cấp", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif.bold", 1, 13), java.awt.Color.black)); // NOI18N
        jPanel3.setForeground(java.awt.Color.black);

        jLabel2.setBackground(java.awt.Color.white);
        jLabel2.setForeground(java.awt.Color.black);
        jLabel2.setText("Mã nhà cung cấp");

        txtMaNhaCungCap.setBackground(java.awt.Color.white);
        txtMaNhaCungCap.setForeground(java.awt.Color.black);

        jLabel3.setBackground(java.awt.Color.white);
        jLabel3.setForeground(java.awt.Color.black);
        jLabel3.setText("SDT nhà cung cấp");

        jLabel4.setBackground(java.awt.Color.white);
        jLabel4.setForeground(java.awt.Color.black);
        jLabel4.setText("Email");

        txtSDTnhaCungCap.setBackground(java.awt.Color.white);
        txtSDTnhaCungCap.setForeground(java.awt.Color.black);

        jLabel5.setBackground(java.awt.Color.white);
        jLabel5.setForeground(java.awt.Color.black);
        jLabel5.setText("Địa chỉ");

        txtDiaChi.setBackground(java.awt.Color.white);
        txtDiaChi.setForeground(java.awt.Color.black);

        jLabel6.setBackground(java.awt.Color.white);
        jLabel6.setForeground(java.awt.Color.black);
        jLabel6.setText("Tên nhà cung cấp");

        txtTenNhaCungCap.setBackground(java.awt.Color.white);
        txtTenNhaCungCap.setForeground(java.awt.Color.black);

        txtEmail.setBackground(java.awt.Color.white);
        txtEmail.setForeground(java.awt.Color.black);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(txtSDTnhaCungCap, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaNhaCungCap, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenNhaCungCap))
                .addGap(71, 71, 71)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(txtEmail))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSDTnhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(java.awt.Color.white);
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm nhà cung cấp", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif.bold", 1, 13), java.awt.Color.black)); // NOI18N
        jPanel4.setForeground(java.awt.Color.black);

        jLabel7.setBackground(java.awt.Color.white);
        jLabel7.setForeground(java.awt.Color.black);
        jLabel7.setText("Mã nhà cung cấp");

        txtTimKiemDiaChiNhaCungCap.setBackground(java.awt.Color.white);
        txtTimKiemDiaChiNhaCungCap.setForeground(java.awt.Color.black);

        jLabel8.setBackground(java.awt.Color.white);
        jLabel8.setForeground(java.awt.Color.black);
        jLabel8.setText("Email");

        txtTimKiemSDTNhaCungCap.setBackground(java.awt.Color.white);
        txtTimKiemSDTNhaCungCap.setForeground(java.awt.Color.black);

        jLabel9.setBackground(java.awt.Color.white);
        jLabel9.setForeground(java.awt.Color.black);
        jLabel9.setText("SDT nhà cung cấp");

        txtTimKiemEmailNhaCungCap.setBackground(java.awt.Color.white);
        txtTimKiemEmailNhaCungCap.setForeground(java.awt.Color.black);

        jLabel10.setBackground(java.awt.Color.white);
        jLabel10.setForeground(java.awt.Color.black);
        jLabel10.setText("Địa chỉ");

        txtTimKiemMaNhaCungCap.setBackground(java.awt.Color.white);
        txtTimKiemMaNhaCungCap.setForeground(java.awt.Color.black);

        jLabel11.setBackground(java.awt.Color.white);
        jLabel11.setForeground(java.awt.Color.black);
        jLabel11.setText("Tên nhà cung cấp");

        txtTimKiemTenNhaCungCap.setBackground(java.awt.Color.white);
        txtTimKiemTenNhaCungCap.setForeground(java.awt.Color.black);

        jButton6.setBackground(java.awt.Color.lightGray);
        jButton6.setForeground(java.awt.Color.black);
        jButton6.setText("Tìm kiếm");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtTimKiemSDTNhaCungCap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(txtTimKiemTenNhaCungCap, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiemMaNhaCungCap, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTimKiemDiaChiNhaCungCap, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                        .addComponent(txtTimKiemEmailNhaCungCap))
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiemDiaChiNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiemMaNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiemEmailNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiemTenNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(1, 1, 1)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiemSDTNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnTableNhaCungCap.setBackground(java.awt.Color.white);
        jpnTableNhaCungCap.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách nhà cung cấp", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif.bold", 1, 13), java.awt.Color.black)); // NOI18N
        jpnTableNhaCungCap.setForeground(java.awt.Color.black);

        javax.swing.GroupLayout jpnTableNhaCungCapLayout = new javax.swing.GroupLayout(jpnTableNhaCungCap);
        jpnTableNhaCungCap.setLayout(jpnTableNhaCungCapLayout);
        jpnTableNhaCungCapLayout.setHorizontalGroup(
            jpnTableNhaCungCapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnTableNhaCungCapLayout.setVerticalGroup(
            jpnTableNhaCungCapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 219, Short.MAX_VALUE)
        );

        jPanel6.setBackground(java.awt.Color.white);

        btnThoat.setBackground(java.awt.Color.white);
        btnThoat.setForeground(java.awt.Color.black);
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnThemNhaCungCap.setBackground(java.awt.Color.white);
        btnThemNhaCungCap.setForeground(java.awt.Color.black);
        btnThemNhaCungCap.setText("Thêm");
        btnThemNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNhaCungCapActionPerformed(evt);
            }
        });

        btnSuaNhaCungCap.setBackground(java.awt.Color.white);
        btnSuaNhaCungCap.setForeground(java.awt.Color.black);
        btnSuaNhaCungCap.setText("Sửa");
        btnSuaNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaNhaCungCapActionPerformed(evt);
            }
        });

        btnXoaNhaCungCap.setBackground(java.awt.Color.white);
        btnXoaNhaCungCap.setForeground(java.awt.Color.black);
        btnXoaNhaCungCap.setText("Xóa");
        btnXoaNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNhaCungCapActionPerformed(evt);
            }
        });

        btnLamMoiNhaCungCap.setBackground(java.awt.Color.white);
        btnLamMoiNhaCungCap.setForeground(java.awt.Color.black);
        btnLamMoiNhaCungCap.setText("Làm mới");
        btnLamMoiNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiNhaCungCapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThemNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSuaNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXoaNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLamMoiNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThoat)
                    .addComponent(btnLamMoiNhaCungCap)
                    .addComponent(btnXoaNhaCungCap)
                    .addComponent(btnSuaNhaCungCap)
                    .addComponent(btnThemNhaCungCap))
                .addContainerGap())
        );

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnRootLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpnRootLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpnTableNhaCungCap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnRootLayout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnTableNhaCungCap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        JPanel node = new jpnHoaDonNhap();
        jpnRoot.removeAll();
        jpnRoot.setLayout(new BorderLayout());
        jpnRoot.add(node);
        jpnRoot.validate();
        jpnRoot.repaint();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnThemNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNhaCungCapActionPerformed
        // TODO add your handling code here:
        QuanLyNhaCungCap quanlyNhaCungCap = new QuanLyNhaCungCap(txtMaNhaCungCap.getText(),txtTenNhaCungCap.getText(),txtSDTnhaCungCap.getText(),txtDiaChi.getText(),txtEmail.getText());
        quanlyNhaCungCap.ThemNhaCungCap(0);
    }//GEN-LAST:event_btnThemNhaCungCapActionPerformed

    private void btnLamMoiNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiNhaCungCapActionPerformed
        // TODO add your handling code here:
        controller.setDataToTable();
    }//GEN-LAST:event_btnLamMoiNhaCungCapActionPerformed

    private void btnSuaNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaNhaCungCapActionPerformed
        // TODO add your handling code here:
        JTable table = controller.getTable();
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        int Row = controller.getRowSua();
        Row = table.convertColumnIndexToModel(Row);
        String txtMaNhaCungCap = model.getValueAt(Row, 1).toString();
        String txtTenNhaCungCap = model.getValueAt(Row, 1).toString();
        String txtSDTnhaCungCap = model.getValueAt(Row, 1).toString();
        String txtDiaChi = model.getValueAt(Row, 1).toString();
        String txtEmail = model.getValueAt(Row, 1).toString();
        
        String sql_Them = "INSERT INTO dbo.nhaCungCap(maNhaCungCap,tenNhaCungCap,sdtNhaCungCap,diaChi,email) " + "VALUES(?,?,?,?,?)";
        try (Connection c = DBConnect.getConnection();
        PreparedStatement ps_Them = c.prepareCall(sql_Them);)
        {
            if( ThemNhaCungCap(1) == 1)
            {
                QuanLyNhaCungCap quanlyNhaCungCap = new QuanLyNhaCungCap(txtMaNhaCungCap,txtTenNhaCungCap,txtSDTnhaCungCap,txtDiaChi,txtEmail);
                quanlyNhaCungCap.XoaSanPham(1);
                ps_Them.setString(1, this.txtMaNhaCungCap.getText()  );
                ps_Them.setString(2, this.txtTenNhaCungCap.getText() );
                ps_Them.setString(3, this.txtSDTnhaCungCap.getText() );
                ps_Them.setString(4, this.txtDiaChi.getText() );
                ps_Them.setString(5, this.txtEmail.getText() );
                ps_Them.executeUpdate();
            }
            
        } catch (Exception ex) {System.out.println(ex.getMessage());}
    }//GEN-LAST:event_btnSuaNhaCungCapActionPerformed

    private void btnXoaNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNhaCungCapActionPerformed
        // TODO add your handling code here:
        QuanLyNhaCungCap quanlyNhaCungCap = new QuanLyNhaCungCap(txtMaNhaCungCap.getText(),txtTenNhaCungCap.getText(),txtSDTnhaCungCap.getText(),txtDiaChi.getText(),txtEmail.getText());
        quanlyNhaCungCap.XoaSanPham(0);
    }//GEN-LAST:event_btnXoaNhaCungCapActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        List<NhaCungCap> listItem = controller.getListNhaCungCap();
        List<NhaCungCap> SearchListItem = new ArrayList<>();
        JTable table = controller.getTable();
        
        for(int i=0;i<listItem.size();i++)
        {
            if(txtTimKiemMaNhaCungCap.getText().length()>0&&listItem.get(i).getMaNhaCungCap().equalsIgnoreCase( txtTimKiemMaNhaCungCap.getText() )== false) continue;
            if(txtTimKiemTenNhaCungCap.getText().length()>0&&listItem.get(i).getTenNhaCungCap().equalsIgnoreCase( txtTimKiemTenNhaCungCap.getText() )== false) continue;
            if(txtTimKiemSDTNhaCungCap.getText().length()>0&&listItem.get(i).getSdtNhaCungCap().equalsIgnoreCase( txtTimKiemSDTNhaCungCap.getText() )== false) continue;
            if(txtTimKiemDiaChiNhaCungCap.getText().length()>0&&listItem.get(i).getDiaChi().equalsIgnoreCase(txtTimKiemDiaChiNhaCungCap.getText() )== false) continue;
            if(txtTimKiemEmailNhaCungCap.getText().length()>0&&listItem.get(i).getEmail().substring(6,10).equalsIgnoreCase( txtTimKiemEmailNhaCungCap.getText() )== false) continue;
            
            SearchListItem.add(listItem.get(i));
        }
        
        ClassTableModel ctm = new ClassTableModel();
        String [] CLOUMNS = controller.getColumnName();
        DefaultTableModel model = ctm.setTableNhaCungCap(SearchListItem, CLOUMNS );
        table.setModel(model);
        
        DefaultTableCellRenderer centerrender = new DefaultTableCellRenderer();

        centerrender.setHorizontalAlignment( JLabel.CENTER );
        
        table.getColumnModel().getColumn(0).setCellRenderer( centerrender );
        
        DefaultTableCellRenderer rightrender = new DefaultTableCellRenderer();
        rightrender.setHorizontalAlignment( JLabel.LEFT );
        table.getColumnModel().getColumn(1).setCellRenderer( rightrender );
        table.getColumnModel().getColumn(2).setCellRenderer( rightrender );
        table.getColumnModel().getColumn(3).setCellRenderer( rightrender );
        table.getColumnModel().getColumn(4).setCellRenderer( rightrender );
        table.getColumnModel().getColumn(5).setCellRenderer( rightrender );
        
        JScrollPane scroll = new JScrollPane();
        scroll.getViewport().add(table);
        scroll.setPreferredSize(new Dimension(1100,330));
        jpnTableNhaCungCap.removeAll();
        jpnTableNhaCungCap.setLayout(new BorderLayout());
        jpnTableNhaCungCap.add(scroll);
        jpnTableNhaCungCap.validate();
        jpnTableNhaCungCap.repaint();
    }//GEN-LAST:event_jButton6ActionPerformed
    
     private int ThemNhaCungCap(int joption ){
        try {
            String errors = "";
            
            if(txtMaNhaCungCap.getText().equals(""))
            {
                errors+= "Mã nhà cung cấp chưa được nhập\n";
                txtMaNhaCungCap.setBackground(Color.red);
            }
            else txtMaNhaCungCap.setBackground(Color.white);
            
            
            
            if(txtTenNhaCungCap.getText().equals(""))
            {
                errors+= "Tên nhà cung cấp chưa được nhập\n";
                txtTenNhaCungCap.setBackground(Color.red);
            }
            else txtTenNhaCungCap.setBackground(Color.white);
            
            
            
            if(txtSDTnhaCungCap.getText().equals(""))
            {
                errors+= "Số điện thoại nhà cung cấp chưa được nhập\n";
                txtSDTnhaCungCap.setBackground(Color.red);
            }
            else txtSDTnhaCungCap.setBackground(Color.white);
            
            if(txtDiaChi.getText().equals(""))
            {
                errors+= "Địa chỉ nhà cung cấp chưa được nhập\n";
                txtDiaChi.setBackground(Color.red);
            }
            else txtDiaChi.setBackground(Color.white);
            
            if(txtEmail.getText().equals(""))
            {
                errors+= "Email chưa được nhập\n";
                txtEmail.setBackground(Color.red);
            }
            else txtEmail.setBackground(Color.white);
            
            
            if(!errors.isEmpty())
            {
                JOptionPane.showMessageDialog(this, errors);
            }
            else
            {
                if(joption==0)
                {
                    String sql = "INSERT INTO dbo.nhaCungCap(maNhaCungCap,tenNhaCungCap,sdtNhaCungCap,diaChi,email) " + "VALUES(?,?,?,?,?)";
                    try (Connection c = DBConnect.getConnection();
                    PreparedStatement ps = c.prepareCall(sql);)
                    {

                        NhaCungCapDAO nhaCungCapDAO = new NhaCungCapDAOImpl();
                        List<NhaCungCap> listNhaCungCap = nhaCungCapDAO.getList();

                        boolean checkMaNhaCungCap=true;
                        for(int i=0;i<listNhaCungCap.size();i++)
                        {
                            if(listNhaCungCap.get(i).getMaNhaCungCap().equals(txtMaNhaCungCap.getText()))
                            {
                                checkMaNhaCungCap = false;
                                break;
                            }
                        }

                        if(checkMaNhaCungCap==false)
                        {
                            JOptionPane.showMessageDialog(this,"Mã nhà cung cấp đã có trong CSDL, hãy nhập SDT khác");
                        }
                        else 
                        {
                            ps.setString(1, txtMaNhaCungCap.getText()  );
                            ps.setString(2, txtTenNhaCungCap.getText() );
                            ps.setString(3, txtSDTnhaCungCap.getText() );
                            ps.setString(4, txtDiaChi.getText() );
                            ps.setString(5, txtEmail.getText() );
                            
                            if(joption==0) 
                            {
                                ps.executeUpdate();
                                JOptionPane.showMessageDialog(this,"Đã THÊM thành công");
                                return 0;
                            }
                        }

                    } catch (Exception ex) { System.out.println("Error " + ex.getMessage());}
                    return 0;
                }
                else 
                {
                    JOptionPane.showMessageDialog(this,"Đã SỬA thành công");
                    return 1;
                }
            }
        } 
        catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Erorr " + e.getMessage());
        }
        return 0;
    }
     private void XoaSanPham(int joption){
        try {
            String errors = "";
            
            if(txtMaNhaCungCap.getText().equals(""))
            {
                errors+= "Mã nhà cung cấp chưa được nhập\n";
                txtMaNhaCungCap.setBackground(Color.red);
            }
            else txtMaNhaCungCap.setBackground(Color.white);
            
            
            
            if(txtTenNhaCungCap.getText().equals(""))
            {
                errors+= "Tên nhà cung cấp chưa được nhập\n";
                txtTenNhaCungCap.setBackground(Color.red);
            }
            else txtTenNhaCungCap.setBackground(Color.white);
            
            
            
            if(txtSDTnhaCungCap.getText().equals(""))
            {
                errors+= "Số điện thoại nhà cung cấp chưa được nhập\n";
                txtSDTnhaCungCap.setBackground(Color.red);
            }
            else txtSDTnhaCungCap.setBackground(Color.white);
            
            if(txtDiaChi.getText().equals(""))
            {
                errors+= "Địa chỉ nhà cung cấp chưa được nhập\n";
                txtDiaChi.setBackground(Color.red);
            }
            else txtDiaChi.setBackground(Color.white);
            
            if(txtEmail.getText().equals(""))
            {
                errors+= "Email chưa được nhập\n";
                txtEmail.setBackground(Color.red);
            }
            else txtEmail.setBackground(Color.white);
            
            
            if(!errors.isEmpty())
            {
                JOptionPane.showMessageDialog(this, errors);
            }
            else
            {
                String sqlnhaCungCap = "DELETE FROM dbo.nhaCungCap  " + "WHERE maNhaCungCap = ?";
                String sqlHoaDonNhap = "DELETE FROM dbo.DanhSachHoaDonNhap " + " WHERE maNhaCungCap = ?";
                String sqlChiTietHoaDonNhap = "DELETE FROM dbo.ChiTietHoaDonNhap " + " WHERE maHoaDonNhap = ?";
                try (Connection c = DBConnect.getConnection();
                PreparedStatement ps_sqlnhaCungCap = c.prepareCall(sqlnhaCungCap);
                PreparedStatement ps_sqlHoaDonNhap = c.prepareCall(sqlHoaDonNhap);
                PreparedStatement ps_ChiTietHoaDonNhap = c.prepareCall(sqlChiTietHoaDonNhap);)
                {
                    ps_sqlnhaCungCap.setString(1, txtMaNhaCungCap.getText());
                    
                    NhaCungCapDAO nhaCungCapDAO = new NhaCungCapDAOImpl();
                    List<NhaCungCap> listNhaCungCap = nhaCungCapDAO.getList();
                    
                    
                    boolean check = false;
                    
                    for(int i=0;i<listNhaCungCap.size();i++)
                    {
                        if(listNhaCungCap.get(i).getMaNhaCungCap().equals(txtMaNhaCungCap.getText()))
                        {
                            check = true;
                            break;
                        }
                    }
                    
                    if(check==true)
                    {
                        ChiTietHoaDonNhapDAO chiTietHoaDonNhapDAO = new ChiTietHoaDonNhapImpl();
                        List<ChiTietHoaDonNhap> listchiTietHoaDonNhap = chiTietHoaDonNhapDAO.getList();
                        
                        HoaDonNhapDAO hoaDonNhapDAO = new HoaDonNhapDAOImpl();
                        List<HoaDonNhap> listHoaDonNhap = hoaDonNhapDAO.getList();
                        
                        for(int i=0;i<listHoaDonNhap.size();i++)
                        {
                            if(listHoaDonNhap.get(i).getNhaCungCap().getMaNhaCungCap().equals(txtMaNhaCungCap.getText().toString()))
                            {
                                ps_ChiTietHoaDonNhap.setString(1, listHoaDonNhap.get(i).getMaHoaDonNhap());
                                ps_ChiTietHoaDonNhap.executeUpdate();
                            }
                        }
                        ps_sqlHoaDonNhap.setString(1, txtMaNhaCungCap.getText().toString());
                        ps_sqlHoaDonNhap.executeUpdate();
                        ps_sqlnhaCungCap.executeUpdate();
                        if(joption==0) JOptionPane.showMessageDialog(this,"Đã XÓA thành công");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this,"Mã nhà cung cấp không đúng vui lòng nhập lại");
                    }
                    
                } catch (Exception ex) {System.out.println(ex.getMessage());}
            }
        } 
        catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Erorr " + e.getMessage());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoiNhaCungCap;
    private javax.swing.JButton btnSuaNhaCungCap;
    private javax.swing.JButton btnThemNhaCungCap;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoaNhaCungCap;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JPanel jpnTableNhaCungCap;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaNhaCungCap;
    private javax.swing.JTextField txtSDTnhaCungCap;
    private javax.swing.JTextField txtTenNhaCungCap;
    private javax.swing.JTextField txtTimKiemDiaChiNhaCungCap;
    private javax.swing.JTextField txtTimKiemEmailNhaCungCap;
    private javax.swing.JTextField txtTimKiemMaNhaCungCap;
    private javax.swing.JTextField txtTimKiemSDTNhaCungCap;
    private javax.swing.JTextField txtTimKiemTenNhaCungCap;
    // End of variables declaration//GEN-END:variables
}
