/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.view;

import com.mycompany.dao.DBConnect;
import com.mycompany.dao.MayTinhDAO;
import com.mycompany.dao.MayTinhDAOImpl;
import com.mycompany.model.KhachHang;
import com.mycompany.model.MayTinh;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class QuanLyChiTietHoaDon extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyChiTietHoaDon
     */
    private int Row = 0;
    private Map<String, Integer> map = new HashMap<>();
    private static JTable table = new JTable();
    private final String [] COLUMNS = {"STT","Sản phẩm","Giá bán","Số lượng","Thành tiền"};
    private DefaultTableModel dtmHoaDon;
    private long tongTien = 0;
    public QuanLyChiTietHoaDon(String txtSoLuong,String txtHinhThucThanhToan, String txtMaHoaDon, String txtNgayBan, String txtNhanVienBanHang, String txtSoDienThoaiKhachHang, String txtTenKhachHang) {
        initComponents();
        this.txtSoLuong.setText(txtSoLuong);
        this.txtHinhThucThanhToan.setText(txtHinhThucThanhToan);
        this.txtMaHoaDon.setText(txtMaHoaDon);
        this.txtNgayBan.setText(txtNgayBan);
        this.txtNhanVienBanHang.setText(txtNhanVienBanHang);
        this.txtSoDienThoai.setText(txtSoDienThoaiKhachHang);
        this.txtTenKhachHang.setText(txtTenKhachHang);
        MayTinhDAO mtd = new MayTinhDAOImpl();
        List<MayTinh> listMayTinh = mtd.getList();
        for(int i=0;i<listMayTinh.size();i++)
        {
            if(map.containsKey(listMayTinh.get(i).getTen_may_tinh())==false)
            {
                map.put(listMayTinh.get(i).getTen_may_tinh(),listMayTinh.get(i).getGia_ban());
                jcbTenMayTinh.addItem(listMayTinh.get(i).getTen_may_tinh());
            }
        }
        this.txtMaHoaDon.setEnabled(false);
        this.txtNhanVienBanHang.setEnabled(false);
        this.txtTenKhachHang.setEnabled(false);
        this.txtSoDienThoai.setEnabled(false);
        this.txtHinhThucThanhToan.setEnabled(false);
        this.txtNgayBan.setEnabled(false);
        dtmHoaDon = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return String.class;
            }
        };
        dtmHoaDon.setColumnIdentifiers(COLUMNS);
        dtmHoaDon.fireTableDataChanged();
        this.jlbTongTien.setBackground(Color.red);
    }

    public QuanLyChiTietHoaDon() {
        initComponents();
        MayTinhDAO mtd = new MayTinhDAOImpl();
        List<MayTinh> listMayTinh = mtd.getList();
        List<String> tenMayTinh = new ArrayList<>();
        jcbTenMayTinh.addItem("");
        for(int i=0;i<listMayTinh.size();i++)
        {
            if(tenMayTinh.contains(listMayTinh.get(i).getTen_may_tinh())==false)
            {
                tenMayTinh.add(listMayTinh.get(i).getTen_may_tinh());
                jcbTenMayTinh.addItem(listMayTinh.get(i).getTen_may_tinh());
            }
        }
        txtMaHoaDon.setEnabled(false);
        txtNhanVienBanHang.setEnabled(false);
        txtTenKhachHang.setEnabled(false);
        txtSoDienThoai.setEnabled(false);
        txtHinhThucThanhToan.setEnabled(false);
        txtNgayBan.setEnabled(false);
        this.jlbTongTien.setBackground(Color.red);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSoDienThoai = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtHinhThucThanhToan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMaHoaDon = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNhanVienBanHang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTenKhachHang = new javax.swing.JTextField();
        txtNgayBan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jcbTenMayTinh = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jpnTableHoaDon = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnThemHoaDon = new javax.swing.JButton();
        btnXoaHoaDon = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jlbTongTien = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();

        jpnRoot.setBackground(java.awt.Color.white);
        jpnRoot.setForeground(java.awt.Color.black);

        jPanel2.setBackground(java.awt.Color.orange);

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel1.setForeground(java.awt.Color.black);
        jLabel1.setText("Quản lý chi tiết hóa đơn bán");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(469, 469, 469)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );

        jPanel3.setBackground(java.awt.Color.white);
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif.bold", 1, 13), java.awt.Color.black)); // NOI18N
        jPanel3.setForeground(java.awt.Color.black);

        jLabel2.setBackground(java.awt.Color.white);
        jLabel2.setForeground(java.awt.Color.black);
        jLabel2.setText("Mã hóa đơn");

        txtSoDienThoai.setBackground(java.awt.Color.white);
        txtSoDienThoai.setForeground(java.awt.Color.black);

        jLabel3.setBackground(java.awt.Color.white);
        jLabel3.setForeground(java.awt.Color.black);
        jLabel3.setText("Nhân viên bán hàng");

        txtHinhThucThanhToan.setBackground(java.awt.Color.white);
        txtHinhThucThanhToan.setForeground(java.awt.Color.black);

        jLabel4.setBackground(java.awt.Color.white);
        jLabel4.setForeground(java.awt.Color.black);
        jLabel4.setText("Tên khách hàng");

        txtMaHoaDon.setBackground(java.awt.Color.white);
        txtMaHoaDon.setForeground(java.awt.Color.black);

        jLabel5.setBackground(java.awt.Color.white);
        jLabel5.setForeground(java.awt.Color.black);
        jLabel5.setText("Số điện thoại");

        txtNhanVienBanHang.setBackground(java.awt.Color.white);
        txtNhanVienBanHang.setForeground(java.awt.Color.black);

        jLabel6.setBackground(java.awt.Color.white);
        jLabel6.setForeground(java.awt.Color.black);
        jLabel6.setText("Hình thức thanh toán");

        txtTenKhachHang.setBackground(java.awt.Color.white);
        txtTenKhachHang.setForeground(java.awt.Color.black);

        txtNgayBan.setBackground(java.awt.Color.white);
        txtNgayBan.setForeground(java.awt.Color.black);

        jLabel7.setBackground(java.awt.Color.white);
        jLabel7.setForeground(java.awt.Color.black);
        jLabel7.setText("Ngày bán");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                    .addComponent(txtNhanVienBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                .addGap(70, 70, 70)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addGap(160, 160, 160))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(txtSoDienThoai))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                        .addGap(104, 104, 104))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHinhThucThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(txtNgayBan))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtHinhThucThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel5))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNhanVienBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        jPanel4.setBackground(java.awt.Color.white);
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin chi tiết hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif.bold", 1, 13), java.awt.Color.black)); // NOI18N
        jPanel4.setForeground(java.awt.Color.black);

        jLabel8.setBackground(java.awt.Color.white);
        jLabel8.setForeground(java.awt.Color.black);
        jLabel8.setText("Tên máy tính");

        jcbTenMayTinh.setBackground(java.awt.Color.white);
        jcbTenMayTinh.setForeground(java.awt.Color.black);

        jLabel9.setBackground(java.awt.Color.white);
        jLabel9.setForeground(java.awt.Color.black);
        jLabel9.setText("Số lượng");

        txtSoLuong.setBackground(java.awt.Color.white);
        txtSoLuong.setForeground(java.awt.Color.black);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbTenMayTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jcbTenMayTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jpnTableHoaDon.setBackground(java.awt.Color.white);
        jpnTableHoaDon.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách hóa đơn ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif.bold", 1, 13), java.awt.Color.black)); // NOI18N
        jpnTableHoaDon.setForeground(java.awt.Color.black);

        javax.swing.GroupLayout jpnTableHoaDonLayout = new javax.swing.GroupLayout(jpnTableHoaDon);
        jpnTableHoaDon.setLayout(jpnTableHoaDonLayout);
        jpnTableHoaDonLayout.setHorizontalGroup(
            jpnTableHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnTableHoaDonLayout.setVerticalGroup(
            jpnTableHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
        );

        jPanel6.setBackground(java.awt.Color.white);
        jPanel6.setForeground(java.awt.Color.black);

        btnThemHoaDon.setBackground(java.awt.Color.white);
        btnThemHoaDon.setForeground(java.awt.Color.black);
        btnThemHoaDon.setText("Thêm");
        btnThemHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemHoaDonActionPerformed(evt);
            }
        });

        btnXoaHoaDon.setBackground(java.awt.Color.white);
        btnXoaHoaDon.setForeground(java.awt.Color.black);
        btnXoaHoaDon.setText("Xóa");
        btnXoaHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaHoaDonActionPerformed(evt);
            }
        });

        btnThoat.setBackground(java.awt.Color.white);
        btnThoat.setForeground(java.awt.Color.black);
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(btnThemHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 343, Short.MAX_VALUE)
                .addComponent(btnXoaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(304, 304, 304)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnXoaHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThoat)
                    .addComponent(btnThemHoaDon))
                .addContainerGap())
        );

        jlbTongTien.setBackground(java.awt.Color.white);
        jlbTongTien.setForeground(java.awt.Color.red);
        jlbTongTien.setText("Tổng tiền");

        txtTongTien.setBackground(java.awt.Color.white);
        txtTongTien.setForeground(java.awt.Color.black);
        txtTongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongTienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpnRootLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jlbTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnRootLayout.createSequentialGroup()
                        .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jpnTableHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(63, 63, 63))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(13, 13, 13)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jpnTableHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(jlbTongTien))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongTienActionPerformed
    private void btnThemHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemHoaDonActionPerformed
        // TODO add your handling code here:
        String errors = "";
        if(txtSoLuong.getText().equals("0"))
        {
            errors+= "Số lượng sản phẩm phải lớn hơn 0 \n";
            txtSoLuong.setBackground(Color.red);
        }
        else txtSoLuong.setBackground(Color.white);
        
        if(jcbTenMayTinh.getSelectedItem().toString().length()==0)
        {
            errors+= "Vui lòng chọn sản phẩm \n";
            jcbTenMayTinh.setBackground(Color.red);
        }
        else jcbTenMayTinh.setBackground(Color.white);
        
        if(errors.length()==0)
        {
            String sql = "INSERT INTO dbo.ChiTietHoaDon(maHoaDon,tenMayTinh,giaBan,soLuong) " + " VALUES(?, ?, ?, ?) ";
            try (Connection c = DBConnect.getConnection();
                PreparedStatement ps = c.prepareCall(sql);){
                
                ps.setString(1, txtMaHoaDon.getText() );
                ps.setString(2, jcbTenMayTinh.getSelectedItem().toString());
                ps.setInt(3,map.get(jcbTenMayTinh.getSelectedItem().toString()));
                ps.setInt(4, Integer.valueOf(txtSoLuong.getText()));
                ps.executeUpdate();
                
                Object[] obj;
                obj = new Object[COLUMNS.length];
                long thanhTien = Long.valueOf(txtSoLuong.getText())*Long.valueOf(map.get(jcbTenMayTinh.getSelectedItem().toString()));
                int SoHang = dtmHoaDon.getRowCount();
                obj[0] = String.valueOf(SoHang + 1);
                obj[1] = jcbTenMayTinh.getSelectedItem().toString();
                obj[2] = map.get(jcbTenMayTinh.getSelectedItem().toString());
                obj[3] = txtSoLuong.getText();
                obj[4] = String.valueOf(thanhTien);
                dtmHoaDon.addRow(obj);
                
                tongTien+= thanhTien;
                txtTongTien.setText(String.valueOf(tongTien));
                
                    JOptionPane.showMessageDialog(this,"Đã THÊM thành công");
                    JTable table = new JTable(dtmHoaDon);
                    table.getTableHeader().setFont(new Font("Arial", Font.BOLD, 12));
                    //table.getTableHeader().setPreferredSize(new Dimension(30, 30));
                    table.setRowHeight(20);
                    table.validate();
                    table.repaint();

                    table.getColumnModel().getColumn(0).setPreferredWidth(10);
                    table.getColumnModel().getColumn(1).setPreferredWidth(15);
                    table.getColumnModel().getColumn(2).setPreferredWidth(15);
                    table.getColumnModel().getColumn(3).setPreferredWidth(15);
                    table.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
                        DefaultTableCellRenderer centerrender = new DefaultTableCellRenderer();
                        centerrender.setHorizontalAlignment(JLabel.CENTER);
                    table.getColumnModel().getColumn(0).setCellRenderer( centerrender );

                      DefaultTableCellRenderer rightrender = new DefaultTableCellRenderer();
                      rightrender.setHorizontalAlignment( JLabel.LEFT );
                    table.getColumnModel().getColumn(1).setCellRenderer( rightrender );
                    table.getColumnModel().getColumn(2).setCellRenderer( rightrender );
                    table.getColumnModel().getColumn(3).setCellRenderer( rightrender );
                    JScrollPane scroll = new JScrollPane();
                    scroll.getViewport().add(table);
                    scroll.setPreferredSize(new Dimension(1110,296));
                    jpnTableHoaDon.removeAll();
                    jpnTableHoaDon.setLayout(new BorderLayout());
                    jpnTableHoaDon.add(scroll);
                    jpnTableHoaDon.validate();
                    jpnTableHoaDon.repaint();
        } catch (Exception ex) {System.out.println(ex.getMessage() + "  hello");}
    }//GEN-LAST:event_btnThemHoaDonActionPerformed
}
    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        JPanel node = new jpnHoaDonBan();
        jpnRoot.removeAll();
        jpnRoot.setLayout(new BorderLayout());
        jpnRoot.add(node);
        jpnRoot.validate();
        jpnRoot.repaint();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnXoaHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaHoaDonActionPerformed
        // TODO add your handling code here:
        String errors = "";
        if(txtSoLuong.getText().equals("0"))
        {
            errors+= "Số lượng sản phẩm phải lớn hơn 0 \n";
            txtSoLuong.setBackground(Color.red);
        }
        else txtSoLuong.setBackground(Color.white);
        
        if(jcbTenMayTinh.getSelectedItem().toString().length()==0)
        {
            errors+= "Vui lòng chọn sản phẩm \n";
            jcbTenMayTinh.setBackground(Color.red);
        }
        else jcbTenMayTinh.setBackground(Color.white);
        
        if(!errors.isEmpty())
        {
            JOptionPane.showMessageDialog(this, errors);
        }
        else
        {
                JTable table = new JTable(dtmHoaDon);
                table.getTableHeader().setFont(new Font("Arial", Font.BOLD, 12));
                //table.getTableHeader().setPreferredSize(new Dimension(30, 30));
                table.setRowHeight(20);
                table.validate();
                table.repaint();
                table.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        if(e.getClickCount()==1&&table.getSelectedRow()!=-1)
                        {
                            dtmHoaDon = (DefaultTableModel) table.getModel();
                            int SelectedRowIndex = table.getSelectedRow();
                            SelectedRowIndex = table.convertColumnIndexToModel(SelectedRowIndex);
                            setRow(SelectedRowIndex);
                        }
                    }
                });
                
                String tenSanPham = dtmHoaDon.getValueAt(this.Row,1 ).toString();
                long giaBan = Long.valueOf(dtmHoaDon.getValueAt(this.Row,2 ).toString());
                long soLuong = Long.valueOf(dtmHoaDon.getValueAt(this.Row,3 ).toString());
                
                long ThanhTien = giaBan * soLuong;        
                table.getColumnModel().getColumn(0).setPreferredWidth(10);
                table.getColumnModel().getColumn(1).setPreferredWidth(15);
                table.getColumnModel().getColumn(2).setPreferredWidth(15);
                table.getColumnModel().getColumn(3).setPreferredWidth(15);
                table.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
                    DefaultTableCellRenderer centerrender = new DefaultTableCellRenderer();
                    centerrender.setHorizontalAlignment(JLabel.CENTER);
                table.getColumnModel().getColumn(0).setCellRenderer( centerrender );

                  DefaultTableCellRenderer rightrender = new DefaultTableCellRenderer();
                  rightrender.setHorizontalAlignment( JLabel.LEFT );
                table.getColumnModel().getColumn(1).setCellRenderer( rightrender );
                table.getColumnModel().getColumn(2).setCellRenderer( rightrender );
                table.getColumnModel().getColumn(3).setCellRenderer( rightrender );
                JScrollPane scroll = new JScrollPane();
                scroll.getViewport().add(table);
                scroll.setPreferredSize(new Dimension(1110,296));
                
                String sql = "DELETE FROM dbo.ChiTietHoaDon  " + "WHERE tenMayTinh = ? ";
                try (Connection c = DBConnect.getConnection();
                PreparedStatement ps = c.prepareCall(sql);)
                {
                    tongTien = Long.valueOf(txtTongTien.getText()) - ThanhTien;
                    txtTongTien.setText(String.valueOf(tongTien));
                    dtmHoaDon.removeRow(this.Row);
                    ps.setString(1,tenSanPham);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this,"Đã XÓA thành công");
                    jpnTableHoaDon.removeAll();
                    jpnTableHoaDon.setLayout(new BorderLayout());
                    jpnTableHoaDon.add(scroll);
                    jpnTableHoaDon.validate();
                    jpnTableHoaDon.repaint();
                } catch (Exception ex) {System.out.println(ex.getMessage());}
        }
        
    }//GEN-LAST:event_btnXoaHoaDonActionPerformed

    public void setRow(int Row){
        this.Row = Row;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThemHoaDon;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoaHoaDon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JComboBox<String> jcbTenMayTinh;
    private javax.swing.JLabel jlbTongTien;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JPanel jpnTableHoaDon;
    private javax.swing.JTextField txtHinhThucThanhToan;
    private javax.swing.JTextField txtMaHoaDon;
    private javax.swing.JTextField txtNgayBan;
    private javax.swing.JTextField txtNhanVienBanHang;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenKhachHang;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
