/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.view;

import com.mycompany.controller.QuanLyNhanVienController;
import com.mycompany.dao.ChiTietHoaDonDAO;
import com.mycompany.dao.ChiTietHoaDonImpl;
import com.mycompany.dao.ChiTietHoaDonNhapDAO;
import com.mycompany.dao.ChiTietHoaDonNhapImpl;
import com.mycompany.dao.ChucVuDAO;
import com.mycompany.dao.ChucVuDAOImpl;
import com.mycompany.dao.DBConnect;
import com.mycompany.dao.HoaDonDAO;
import com.mycompany.dao.HoaDonDAOImpl;
import com.mycompany.dao.HoaDonNhapDAO;
import com.mycompany.dao.HoaDonNhapDAOImpl;
import com.mycompany.dao.MayTinhDAO;
import com.mycompany.dao.MayTinhDAOImpl;
import com.mycompany.dao.NhanVienDAOImpl;
import com.mycompany.dao.NhanVienDao;
import com.mycompany.model.ChiTietHoaDon;
import com.mycompany.model.ChiTietHoaDonNhap;
import com.mycompany.model.ChucVu;
import com.mycompany.model.HoaDonBan;
import com.mycompany.model.HoaDonNhap;
import com.mycompany.model.MayTinh;
import com.mycompany.model.NhanVien;
import com.mycompany.utility.ClassTableModel;
import com.toedter.calendar.JDateChooser;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import java.time.*;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableCellRenderer;
/**
 *
 * @author Admin
 */
public class QuanLyNhanVien extends javax.swing.JPanel {
    
    private JRadioButton [] jrbGioiTinhNV;
    public QuanLyNhanVien(JTextField txtMaNhanVien,JTextField txtTenNhanVien,JTextField txtNgaySinh,JRadioButton[] jrbGioiTinhNV,JTextField txtSoDienThoaiNhanVien, JTextField txtEmail,JComboBox<String> jcbChucVu) {
        this.txtMaNhanVien = txtMaNhanVien;
        this.txtTenNhanVien = txtTenNhanVien;
        
        if(jrbGioiTinhNV[0].isSelected()==false)
        {
            jrbGioiTinhNV[1].setSelected(true);
        }
        else jrbGioiTinhNV[0].setSelected(true);
        this.txtNgaySinh = txtNgaySinh;
        this.txtSoDienThoaiNV = txtSoDienThoaiNhanVien;
        this.txtEmail = txtEmail;
        this.jcbChucVu = jcbChucVu;
        this.jrbNam = jrbGioiTinhNV[0];
        this.jrbNu = jrbGioiTinhNV[1];
    }

    
    QuanLyNhanVienController controller = null;
    public QuanLyNhanVien() {
        initComponents();
        jrbGioiTinhNV = new JRadioButton[2];
        jrbGioiTinhNV[0] = jrbNam;
        jrbGioiTinhNV[1] = jrbNu;
        QuanLyNhanVien qlnv = new QuanLyNhanVien(txtMaNhanVien, txtTenNhanVien, txtNgaySinh ,jrbGioiTinhNV, txtSoDienThoaiNV, txtEmail, jcbChucVu);
        controller = new QuanLyNhanVienController(txtMaNhanVien, txtTenNhanVien, txtNgaySinh, jrbGioiTinhNV, txtSoDienThoaiNV, txtEmail, jcbChucVu, jpnTableQLNV);
        controller.setDataToTable();
        jpnChucNangNV.validate();
        jpnChucNangNV.repaint();
        jcbChucVu.addItem("");
        ChucVuDAO cvd = new ChucVuDAOImpl();
        List<ChucVu> list_chuc_vu = cvd.getList();
        for(int i=0;i<list_chuc_vu.size();i++)
        {
            jcbChucVu.addItem(list_chuc_vu.get(i).getTen_chuc_vu());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jDialog3 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jlbCanhBao = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMaNhanVien = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTenNhanVien = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSoDienThoaiNV = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnQLCV = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jrbNam = new javax.swing.JRadioButton();
        jrbNu = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jcbChucVu = new javax.swing.JComboBox<>();
        txtNgaySinh = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtTimKiemMaNV = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTimKiemTenNV = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTimKiemSDTNV = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnTimKiemNhanVien = new javax.swing.JButton();
        txtTimKiemNamSinhNV = new javax.swing.JTextField();
        jcbTimKiemChucVuNV = new javax.swing.JComboBox<>();
        jpnTableQLNV = new javax.swing.JPanel();
        jpnChucNangNV = new javax.swing.JPanel();
        btnThemNV = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnSuaNhanVien = new javax.swing.JButton();
        btnXoaNhanVien = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setForeground(java.awt.Color.black);

        jlbCanhBao.setBackground(java.awt.Color.white);
        jlbCanhBao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Nhân Viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif.bold", 1, 13), java.awt.Color.black)); // NOI18N
        jlbCanhBao.setForeground(java.awt.Color.black);
        jlbCanhBao.setName(""); // NOI18N

        jLabel2.setForeground(java.awt.Color.black);
        jLabel2.setText("Mã Nhân Viên");

        txtMaNhanVien.setBackground(java.awt.Color.white);
        txtMaNhanVien.setForeground(java.awt.Color.black);
        txtMaNhanVien.setOpaque(true);
        txtMaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNhanVienActionPerformed(evt);
            }
        });

        jLabel3.setBackground(java.awt.Color.white);
        jLabel3.setForeground(java.awt.Color.black);
        jLabel3.setText("Tên Nhân Viên");

        txtTenNhanVien.setBackground(java.awt.Color.white);
        txtTenNhanVien.setForeground(java.awt.Color.black);

        jLabel4.setBackground(java.awt.Color.white);
        jLabel4.setForeground(java.awt.Color.black);
        jLabel4.setText("Số Điện Thoại");

        txtSoDienThoaiNV.setBackground(java.awt.Color.white);
        txtSoDienThoaiNV.setForeground(java.awt.Color.black);

        jLabel5.setBackground(java.awt.Color.white);
        jLabel5.setForeground(java.awt.Color.black);
        jLabel5.setText("Email");

        txtEmail.setBackground(java.awt.Color.white);
        txtEmail.setForeground(java.awt.Color.black);

        jLabel6.setBackground(java.awt.Color.white);
        jLabel6.setForeground(java.awt.Color.black);
        jLabel6.setText("Chức Vụ");

        btnQLCV.setBackground(java.awt.Color.lightGray);
        btnQLCV.setForeground(java.awt.Color.black);
        btnQLCV.setText("QLCV");

        jLabel7.setBackground(java.awt.Color.white);
        jLabel7.setForeground(java.awt.Color.black);
        jLabel7.setText("Ngày Sinh");

        jrbNam.setBackground(java.awt.Color.white);
        buttonGroup1.add(jrbNam);
        jrbNam.setForeground(java.awt.Color.black);
        jrbNam.setText("Nam");
        jrbNam.setName(""); // NOI18N
        jrbNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbNamActionPerformed(evt);
            }
        });

        jrbNu.setBackground(java.awt.Color.white);
        buttonGroup1.add(jrbNu);
        jrbNu.setForeground(java.awt.Color.black);
        jrbNu.setSelected(true);
        jrbNu.setText("Nữ");
        jrbNu.setBorder(null);
        jrbNu.setBorderPainted(true);
        jrbNu.setName(""); // NOI18N
        jrbNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbNuActionPerformed(evt);
            }
        });

        jLabel8.setBackground(java.awt.Color.white);
        jLabel8.setForeground(java.awt.Color.black);
        jLabel8.setText("Giới Tính:");

        jcbChucVu.setBackground(java.awt.Color.white);
        jcbChucVu.setForeground(java.awt.Color.black);

        txtNgaySinh.setBackground(java.awt.Color.white);
        txtNgaySinh.setForeground(java.awt.Color.black);
        txtNgaySinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgaySinhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jlbCanhBaoLayout = new javax.swing.GroupLayout(jlbCanhBao);
        jlbCanhBao.setLayout(jlbCanhBaoLayout);
        jlbCanhBaoLayout.setHorizontalGroup(
            jlbCanhBaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlbCanhBaoLayout.createSequentialGroup()
                .addGroup(jlbCanhBaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlbCanhBaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtMaNhanVien)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoDienThoaiNV, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jlbCanhBaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlbCanhBaoLayout.createSequentialGroup()
                        .addGroup(jlbCanhBaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jlbCanhBaoLayout.createSequentialGroup()
                        .addGroup(jlbCanhBaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jlbCanhBaoLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jlbCanhBaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jlbCanhBaoLayout.createSequentialGroup()
                                        .addComponent(jrbNam)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrbNu, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnQLCV, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jlbCanhBaoLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(12, Short.MAX_VALUE))))
            .addGroup(jlbCanhBaoLayout.createSequentialGroup()
                .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jlbCanhBaoLayout.setVerticalGroup(
            jlbCanhBaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlbCanhBaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlbCanhBaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jlbCanhBaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jlbCanhBaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(12, 12, 12)
                .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jlbCanhBaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jrbNam)
                    .addComponent(jrbNu)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jlbCanhBaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jlbCanhBaoLayout.createSequentialGroup()
                        .addComponent(txtSoDienThoaiNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnQLCV, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 23, Short.MAX_VALUE))
        );

        jrbNu.getAccessibleContext().setAccessibleDescription("");

        jPanel4.setBackground(java.awt.Color.white);
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm Kiếm Nhân Viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif.bold", 1, 13), java.awt.Color.black)); // NOI18N
        jPanel4.setForeground(java.awt.Color.black);
        jPanel4.setToolTipText("");

        jLabel9.setBackground(java.awt.Color.white);
        jLabel9.setForeground(java.awt.Color.black);
        jLabel9.setText("Mã Nhân Viên");

        txtTimKiemMaNV.setBackground(java.awt.Color.white);
        txtTimKiemMaNV.setForeground(java.awt.Color.black);
        txtTimKiemMaNV.setToolTipText("");
        txtTimKiemMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemMaNVActionPerformed(evt);
            }
        });

        jLabel10.setBackground(java.awt.Color.white);
        jLabel10.setForeground(java.awt.Color.black);
        jLabel10.setText("Tên Nhân Viên");

        txtTimKiemTenNV.setBackground(java.awt.Color.white);
        txtTimKiemTenNV.setForeground(java.awt.Color.black);
        txtTimKiemTenNV.setToolTipText("");

        jLabel11.setBackground(java.awt.Color.white);
        jLabel11.setForeground(java.awt.Color.black);
        jLabel11.setText("Số Điện Thoại");

        txtTimKiemSDTNV.setBackground(java.awt.Color.white);
        txtTimKiemSDTNV.setForeground(java.awt.Color.black);
        txtTimKiemSDTNV.setToolTipText("");

        jLabel12.setBackground(java.awt.Color.white);
        jLabel12.setForeground(java.awt.Color.black);
        jLabel12.setText("Chức Vụ");

        jLabel13.setBackground(java.awt.Color.white);
        jLabel13.setForeground(java.awt.Color.black);
        jLabel13.setText("Năm Sinh");

        btnTimKiemNhanVien.setBackground(java.awt.Color.lightGray);
        btnTimKiemNhanVien.setForeground(java.awt.Color.black);
        btnTimKiemNhanVien.setText("Tìm Kiếm");
        btnTimKiemNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemNhanVienActionPerformed(evt);
            }
        });

        txtTimKiemNamSinhNV.setBackground(java.awt.Color.white);
        txtTimKiemNamSinhNV.setForeground(java.awt.Color.black);

        jcbTimKiemChucVuNV.setBackground(java.awt.Color.white);
        jcbTimKiemChucVuNV.setForeground(java.awt.Color.black);
        jcbTimKiemChucVuNV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nhân viên bán hàng", "quản lý" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtTimKiemSDTNV)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                        .addComponent(txtTimKiemMaNV)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTimKiemTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTimKiemNamSinhNV, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(95, 95, 95))
                        .addComponent(btnTimKiemNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jcbTimKiemChucVuNV, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcbTimKiemChucVuNV)
                    .addComponent(txtTimKiemMaNV))
                .addGap(13, 13, 13)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(txtTimKiemTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTimKiemNamSinhNV, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15)
                .addComponent(jLabel11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(txtTimKiemSDTNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(73, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTimKiemNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );

        jpnTableQLNV.setBackground(java.awt.Color.white);
        jpnTableQLNV.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quản lý nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif.bold", 1, 13), java.awt.Color.black)); // NOI18N
        jpnTableQLNV.setForeground(java.awt.Color.black);
        jpnTableQLNV.setToolTipText("");

        javax.swing.GroupLayout jpnTableQLNVLayout = new javax.swing.GroupLayout(jpnTableQLNV);
        jpnTableQLNV.setLayout(jpnTableQLNVLayout);
        jpnTableQLNVLayout.setHorizontalGroup(
            jpnTableQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnTableQLNVLayout.setVerticalGroup(
            jpnTableQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
        );

        jpnChucNangNV.setBackground(java.awt.Color.white);
        jpnChucNangNV.setForeground(java.awt.Color.black);

        btnThemNV.setBackground(java.awt.Color.white);
        btnThemNV.setForeground(java.awt.Color.black);
        btnThemNV.setText("Thêm ");
        btnThemNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNVActionPerformed(evt);
            }
        });

        btnLamMoi.setBackground(java.awt.Color.white);
        btnLamMoi.setForeground(java.awt.Color.black);
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnSuaNhanVien.setBackground(java.awt.Color.white);
        btnSuaNhanVien.setForeground(java.awt.Color.black);
        btnSuaNhanVien.setText("Sửa");
        btnSuaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaNhanVienActionPerformed(evt);
            }
        });

        btnXoaNhanVien.setBackground(java.awt.Color.white);
        btnXoaNhanVien.setForeground(java.awt.Color.black);
        btnXoaNhanVien.setText("Xóa");
        btnXoaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNhanVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnChucNangNVLayout = new javax.swing.GroupLayout(jpnChucNangNV);
        jpnChucNangNV.setLayout(jpnChucNangNVLayout);
        jpnChucNangNVLayout.setHorizontalGroup(
            jpnChucNangNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnChucNangNVLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btnThemNV, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160)
                .addComponent(btnSuaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                .addComponent(btnXoaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160)
                .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        jpnChucNangNVLayout.setVerticalGroup(
            jpnChucNangNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnChucNangNVLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jpnChucNangNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemNV)
                    .addComponent(btnLamMoi)
                    .addComponent(btnXoaNhanVien)
                    .addComponent(btnSuaNhanVien))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpnTableQLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnChucNangNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlbCanhBao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlbCanhBao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnTableQLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnChucNangNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(java.awt.Color.yellow);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.red);
        jLabel1.setText("Quản Lý Nhân Viên");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(275, 275, 275))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNhanVienActionPerformed

    private void jrbNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbNamActionPerformed

    private void jrbNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbNuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbNuActionPerformed

    private void txtTimKiemMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemMaNVActionPerformed

    private void btnThemNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNVActionPerformed
        // TODO add your handling code here:
        jrbGioiTinhNV = new JRadioButton[2];
        jrbGioiTinhNV[0] = jrbNam;
        jrbGioiTinhNV[1] = jrbNu;
//        ngaySinhNV = controller.getNgaySinh();
//        controller = new QuanLyNhanVienController(txtMaNhanVien, txtTenNhanVien, jdateNgaySinhNV, jrbGioiTinhNV, txtSoDienThoaiNV, txtEmail, jcbChucVu, jpnTableQLNV);
        QuanLyNhanVien qlnv = new QuanLyNhanVien(txtMaNhanVien, txtTenNhanVien, txtNgaySinh ,jrbGioiTinhNV, txtSoDienThoaiNV, txtEmail, jcbChucVu);
        qlnv.ThemNhanVien(0);
        
    }//GEN-LAST:event_btnThemNVActionPerformed
    private void XoaNhanVien(){
        try {
            String errors = "";
            if(txtMaNhanVien.getText().equals(""))
            {
                errors += "Mã nhân viên chưa được nhập\n";
                txtMaNhanVien.setBackground(Color.red);
            }
            else    txtMaNhanVien.setBackground(Color.WHITE);
           
            
            if(txtTenNhanVien.getText().equals(""))
            {
                errors+= "Tên nhân viên chưa được nhập\n";
                txtTenNhanVien.setBackground(Color.red);
            }
            else txtTenNhanVien.setBackground(Color.white);
            
        
            
            if(txtNgaySinh.getText().equals(""))
            {
                errors+= "Ngày sinh chưa được nhập\n";
                txtNgaySinh.setBackground(Color.red);
            }
            else txtNgaySinh.setBackground(Color.white);
            
            if(txtSoDienThoaiNV.getText().equals(""))
            {
                errors+= "Số điện thoại chưa được nhập\n";
                txtSoDienThoaiNV.setBackground(Color.red);
            }
            else txtSoDienThoaiNV.setBackground(Color.white);
            
            if(txtEmail.getText().equals(""))
            {
                errors+= "Email chưa được nhập";
                txtEmail.setBackground(Color.red);
            }
            else txtEmail.setBackground(Color.white);
            
            if(jcbChucVu.getSelectedItem().toString().equals(""))
            {
                errors+= "Email chưa được nhập";
                jcbChucVu.setBackground(Color.red);
            }
            else jcbChucVu.setBackground(Color.white);
            
            if(!errors.isEmpty())
            {
                JOptionPane.showMessageDialog(this, errors);
            }
            else
            {
                
                
                String sql_NhanVien = "DELETE FROM dbo.Nhan_vien  " + "WHERE ma_nhan_vien = ?";
                String sql_ChiTietHoaDon = "DELETE FROM dbo.ChiTietHoaDon  " + "WHERE maHoaDon = ?";
                String sql_DanhSachHoaDon = "DELETE FROM dbo.Danh_sach_hoa_don  " + "WHERE ma_nhan_vien = ?";
                String sql_ChiTietHoaDonNhap = "DELETE FROM dbo.ChiTietHoaDonNhap  " + "WHERE maHoaDonNhap = ?";
                String sql_DanhSachHoaDonNhap = "DELETE FROM dbo.DanhSachHoaDonNhap  " + "WHERE maNhanVien = ?";
                //String sql_NhaCungCap = "DELETE FROM dbo.Nhan_vien  " + "WHERE ma_nhan_vien = ?";
                try (Connection c = DBConnect.getConnection();
                PreparedStatement ps_XoaNhanVien = c.prepareCall(sql_NhanVien);
                PreparedStatement ps_ChiTietHoaDon = c.prepareCall(sql_ChiTietHoaDon);
                PreparedStatement ps_DanhSachHoaDon = c.prepareCall(sql_DanhSachHoaDon);
                PreparedStatement ps_ChiTietHoaDonNhap = c.prepareCall(sql_ChiTietHoaDonNhap);
                PreparedStatement ps_DanhSachHoaDonNhap = c.prepareCall(sql_DanhSachHoaDonNhap);)
                {
                    ps_XoaNhanVien.setString(1, txtMaNhanVien.getText());
                    
                    NhanVienDao nvd = new NhanVienDAOImpl();
                    List<NhanVien> list_nhan_vien = nvd.getListNhanVien();
                    
                    ChiTietHoaDonDAO chiTietHoaDonDAO = new ChiTietHoaDonImpl();
                    List<ChiTietHoaDon> listChiTietHoaDon = chiTietHoaDonDAO.getList();
                    
                    HoaDonDAO hoaDonDAO = new HoaDonDAOImpl();
                    List<HoaDonBan> listHoaDonBan = hoaDonDAO.getList();
                    
                    ChiTietHoaDonNhapDAO chiTietHoaDonNhap = new ChiTietHoaDonNhapImpl();
                    List<ChiTietHoaDonNhap> listChiTietHoaDonNhap = chiTietHoaDonNhap.getList();
                    
                    HoaDonNhapDAO hoaDonNhapDAO = new HoaDonNhapDAOImpl();
                    List<HoaDonNhap> listHoaDonNhap = hoaDonNhapDAO.getList();
                    
                    boolean check = false;
                    for(int i=0;i<list_nhan_vien.size();i++)
                    {
                        if(list_nhan_vien.get(i).getMa_nhan_vien().equals(txtMaNhanVien.getText()))
                        {
                            check = true;
                            break;
                        }
                    }
                    
                    if(check==true)
                    {
                        for(int i=0;i<listHoaDonBan.size();i++)
                        {
                            if(listHoaDonBan.get(i).getNhan_vien_ban_hang().getMa_nhan_vien().equals(txtMaNhanVien.getText()))
                            {
                                ps_ChiTietHoaDon.setString(1, listHoaDonBan.get(i).getMaHoaDonBan());
                                ps_ChiTietHoaDon.executeUpdate();
                            }
                        }
                        ps_DanhSachHoaDon.setString(1, txtMaNhanVien.getText());
                        ps_DanhSachHoaDon.executeUpdate();
                        for(int i=0;i<listHoaDonNhap.size();i++)
                        {
                            if(listHoaDonNhap.get(i).getNhanVien().getMa_nhan_vien().equals(txtMaNhanVien.getText()))
                            {
                                ps_ChiTietHoaDonNhap.setString(1, listHoaDonNhap.get(i).getMaHoaDonNhap());
                                ps_ChiTietHoaDonNhap.executeUpdate();
                            }
                        }
                        ps_DanhSachHoaDonNhap.setString(1, txtMaNhanVien.getText());
                        ps_DanhSachHoaDonNhap.executeUpdate();
                        ps_XoaNhanVien.executeUpdate();
                        JOptionPane.showMessageDialog(this,"Đã XÓA thành công");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this,"Mã nhân viên không có trong cơ sở dữ liệu");
                    }
                    
                } catch (Exception ex) {JOptionPane.showMessageDialog(this,"Không thể xóa nhân viên do xung đột dữ liệu");}
            }
        } 
        catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Erorr " + e.getMessage());
        }
    }
    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        controller.setDataToTable();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnSuaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaNhanVienActionPerformed
        // TODO add your handling code here:
         JTable table = controller.getTable();
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        int Row = controller.getRowSua();
        Row = table.convertColumnIndexToModel(Row);
        String maNhanVien = model.getValueAt(Row, 1).toString();
        String sql_NhanVien = "DELETE FROM dbo.Nhan_vien  " + "WHERE ma_nhan_vien = ?";
        String sql_ChiTietHoaDon = "DELETE FROM dbo.ChiTietHoaDon  " + "WHERE maHoaDon = ?";
        String sql_DanhSachHoaDon = "DELETE FROM dbo.Danh_sach_hoa_don  " + "WHERE ma_nhan_vien = ?";
        String sql_ChiTietHoaDonNhap = "DELETE FROM dbo.ChiTietHoaDonNhap  " + "WHERE maHoaDonNhap = ?";
        String sql_DanhSachHoaDonNhap = "DELETE FROM dbo.DanhSachHoaDonNhap  " + "WHERE maNhanVien = ?";
         
        String sql_insertNhanVien = "INSERT INTO dbo.Nhan_vien(ma_nhan_vien,ten_nhan_vien,ngay_sinh,gioi_tinh,so_dien_thoai,email,chuc_vu) " + " VALUES(?,?,?,?,?,?,?)";
        try (Connection c = DBConnect.getConnection();
        PreparedStatement ps_ThemNhanVien = c.prepareCall(sql_insertNhanVien);
        PreparedStatement ps_XoaNhanVien = c.prepareCall(sql_NhanVien);
        PreparedStatement ps_ChiTietHoaDon = c.prepareCall(sql_ChiTietHoaDon);
        PreparedStatement ps_DanhSachHoaDon = c.prepareCall(sql_DanhSachHoaDon);
        PreparedStatement ps_ChiTietHoaDonNhap = c.prepareCall(sql_ChiTietHoaDonNhap);
        PreparedStatement ps_DanhSachHoaDonNhap = c.prepareCall(sql_DanhSachHoaDonNhap);)
        {
            if( ThemNhanVien (1) == 1)
            {
                
                    
                NhanVienDao nvd = new NhanVienDAOImpl();
                List<NhanVien> list_nhan_vien = nvd.getListNhanVien();

                ChiTietHoaDonDAO chiTietHoaDonDAO = new ChiTietHoaDonImpl();
                List<ChiTietHoaDon> listChiTietHoaDon = chiTietHoaDonDAO.getList();

                HoaDonDAO hoaDonDAO = new HoaDonDAOImpl();
                List<HoaDonBan> listHoaDonBan = hoaDonDAO.getList();

                ChiTietHoaDonNhapDAO chiTietHoaDonNhap = new ChiTietHoaDonNhapImpl();
                List<ChiTietHoaDonNhap> listChiTietHoaDonNhap = chiTietHoaDonNhap.getList();

                HoaDonNhapDAO hoaDonNhapDAO = new HoaDonNhapDAOImpl();
                List<HoaDonNhap> listHoaDonNhap = hoaDonNhapDAO.getList();

                boolean check = false;
                for(int i=0;i<list_nhan_vien.size();i++)
                {
                    if(list_nhan_vien.get(i).getMa_nhan_vien().equals(maNhanVien))
                    {
                        check = true;
                        break;
                    }
                }
                    
                if(check==true)
                {
                    for(int i=0;i<listHoaDonBan.size();i++)
                    {
                        if(listHoaDonBan.get(i).getNhan_vien_ban_hang().getMa_nhan_vien().equals(maNhanVien))
                        {
                            ps_ChiTietHoaDon.setString(1, listHoaDonBan.get(i).getMaHoaDonBan());
                            ps_ChiTietHoaDon.executeUpdate();
                        }
                    }
                    ps_DanhSachHoaDon.setString(1, maNhanVien);
                    ps_DanhSachHoaDon.executeUpdate();
                    
                    for(int i=0;i<listHoaDonNhap.size();i++)
                    {
                        if(listHoaDonNhap.get(i).getNhanVien().getMa_nhan_vien().equals(maNhanVien))
                        {
                            ps_ChiTietHoaDonNhap.setString(1, listHoaDonNhap.get(i).getMaHoaDonNhap());
                            ps_ChiTietHoaDonNhap.executeUpdate();
                        }
                    }
                    
                    ps_DanhSachHoaDonNhap.setString(1, maNhanVien);
                    ps_DanhSachHoaDonNhap.executeUpdate();
                    ps_XoaNhanVien.setString(1, maNhanVien);
                    ps_XoaNhanVien.executeUpdate();
                    
                    Date date = new SimpleDateFormat("dd/MM/yyyy").parse(txtNgaySinh.getText().toString());
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                    String gioiTinh = "";
                    if(jrbNam.isSelected()==true) gioiTinh = "Nam";
                    else gioiTinh ="Nữ";
                    ps_DanhSachHoaDonNhap.setString(1, txtMaNhanVien.getText());
                    ps_DanhSachHoaDonNhap.executeUpdate();
                    ps_XoaNhanVien.executeUpdate();
                    ps_ThemNhanVien.setString(1, txtMaNhanVien.getText());
                    ps_ThemNhanVien.setString(2, txtTenNhanVien.getText());
                    ps_ThemNhanVien.setString(3, sdf.format(date));
                    ps_ThemNhanVien.setString(4, gioiTinh);
                    ps_ThemNhanVien.setString(5, txtSoDienThoaiNV.getText());
                    ps_ThemNhanVien.setString(6, txtEmail.getText());
                    ps_ThemNhanVien.setString(7, jcbChucVu.getSelectedItem().toString());
                    ps_ThemNhanVien.executeUpdate();
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Mã nhân viên không có trong cơ sở dữ liệu");
                }
            }
    }
        catch(Exception ex) {System.out.println(ex.getMessage());};
    }//GEN-LAST:event_btnSuaNhanVienActionPerformed

    private void btnXoaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNhanVienActionPerformed
        // TODO add your handling code here:
        QuanLyNhanVien qlnv = new QuanLyNhanVien(txtMaNhanVien, txtTenNhanVien, txtNgaySinh ,jrbGioiTinhNV, txtSoDienThoaiNV, txtEmail, jcbChucVu);
        qlnv.XoaNhanVien();
    }//GEN-LAST:event_btnXoaNhanVienActionPerformed

    private void btnTimKiemNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemNhanVienActionPerformed
        // TODO add your handling code here:
        
        List<NhanVien> listItem = controller.getListNhanVien();
        List<NhanVien> SearchListItem = new ArrayList<>();
        JTable table = controller.getTable();
        jcbTimKiemChucVuNV.addItem("");
        ChucVuDAO cvd = new ChucVuDAOImpl();
        List<ChucVu> list_chuc_vu = cvd.getList();
        for(int i=0;i<list_chuc_vu.size();i++)
        {
            jcbTimKiemChucVuNV.addItem(list_chuc_vu.get(i).getTen_chuc_vu());
        }
        for(int i=0;i<listItem.size();i++)
        {
            if(txtTimKiemMaNV.getText().length()>0&&listItem.get(i).getMa_nhan_vien().equalsIgnoreCase( txtTimKiemMaNV.getText() )== false) continue;
            if(txtTimKiemTenNV.getText().length()>0&&listItem.get(i).getTen_nhan_vien().equalsIgnoreCase( txtTimKiemTenNV.getText() )== false) continue;
            if(txtTimKiemSDTNV.getText().length()>0&&listItem.get(i).getSo_dien_thoai().equalsIgnoreCase( txtTimKiemSDTNV.getText() )== false) continue;
            if(jcbTimKiemChucVuNV.getSelectedItem().toString().length()>0&&listItem.get(i).getChuc_vu().equalsIgnoreCase( jcbTimKiemChucVuNV.getSelectedItem().toString() )== false) continue;
            if(txtTimKiemNamSinhNV.getText().length()>0&&listItem.get(i).getNgaySinh().substring(6,10).equalsIgnoreCase( txtTimKiemNamSinhNV.getText() )== false) continue;
            
            SearchListItem.add(listItem.get(i));
        }
        
        ClassTableModel ctm = new ClassTableModel();
        String [] CLOUMNS = controller.getColumnName();
        DefaultTableModel model = ctm.setTableNhanVien(SearchListItem, CLOUMNS );
        table.setModel(model);
        
        DefaultTableCellRenderer centerrender = new DefaultTableCellRenderer();

        centerrender.setHorizontalAlignment( JLabel.CENTER );
        
        table.getColumnModel().getColumn(0).setCellRenderer( centerrender );
        
        DefaultTableCellRenderer rightrender = new DefaultTableCellRenderer();
        rightrender.setHorizontalAlignment( JLabel.LEFT );
        table.getColumnModel().getColumn(1).setCellRenderer( rightrender );
        table.getColumnModel().getColumn(2).setCellRenderer( rightrender );
        table.getColumnModel().getColumn(3).setCellRenderer( rightrender );
        table.getColumnModel().getColumn(4).setCellRenderer( rightrender );
        table.getColumnModel().getColumn(5).setCellRenderer( rightrender );
        table.getColumnModel().getColumn(6).setCellRenderer( rightrender );
        table.getColumnModel().getColumn(7).setCellRenderer( rightrender );  
        
        JScrollPane scroll = new JScrollPane();
        scroll.getViewport().add(table);
        scroll.setPreferredSize(new Dimension(1350,330));
        jpnTableQLNV.removeAll();
        jpnTableQLNV.setLayout(new BorderLayout());
        jpnTableQLNV.add(scroll);
        jpnTableQLNV.validate();
        jpnTableQLNV.repaint();
    }//GEN-LAST:event_btnTimKiemNhanVienActionPerformed

    private void txtNgaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgaySinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgaySinhActionPerformed
    private int ThemNhanVien(int joption ){
        try {
            String errors = "";
            if(txtMaNhanVien.getText().equals(""))
            {
                errors += "Mã nhân viên chưa được nhập\n";
                txtMaNhanVien.setBackground(Color.red);
            }
            else    txtMaNhanVien.setBackground(Color.WHITE);
           
            
            if(txtTenNhanVien.getText().equals(""))
            {
                errors+= "Tên máy tính chưa được nhập\n";
                txtTenNhanVien.setBackground(Color.red);
            }
            else txtTenNhanVien.setBackground(Color.white);
            
            
            if(txtNgaySinh.equals(""))
            {
                errors+= "Ngày sinh chưa được nhập\n";
                txtNgaySinh.setBackground(Color.red);
            }
            else
            {
                int year_now = LocalDate.now().getYear();
                int year_nhan_vien =Integer.parseInt(txtNgaySinh.getText().substring(6,10));
                if(year_now-year_nhan_vien<18) 
                {
                    errors+= "Nhân viên không được nhỏ hơn 18 tuổi \n";
                    txtNgaySinh.setBackground(Color.red);
                }
                else txtNgaySinh.setBackground(Color.white);
            }
            
            if(txtSoDienThoaiNV.getText().equals(""))
            {
                errors+= "Số điện thoại chưa được nhập";
                txtSoDienThoaiNV.setBackground(Color.red);
            }
            else txtSoDienThoaiNV.setBackground(Color.white);
            
            if(txtEmail.getText().equals(""))
            {
                errors+= "Email chưa được nhập";
                txtEmail.setBackground(Color.red);
            }
            else txtEmail.setBackground(Color.white);
            
            if(jcbChucVu.getSelectedItem().toString().equals(""))
            {
                errors+= "Chức vụ chưa được nhập";
                jcbChucVu.setBackground(Color.red);
            }
            else jcbChucVu.setBackground(Color.white);
            
            if(!errors.isEmpty())
            {
                JOptionPane.showMessageDialog(this, errors);
            }
            else
            {
                String sql = "INSERT INTO dbo.Nhan_vien(ma_nhan_vien,ten_nhan_vien,ngay_sinh,gioi_tinh,so_dien_thoai, email,chuc_vu) " + " VALUES(?, ?, ?, ? , ? , ?, ? ) ";
                try (Connection c = DBConnect.getConnection();
                PreparedStatement ps = c.prepareCall(sql); )
                {
                    String tmp = "";
                    tmp = txtNgaySinh.getText().substring(6,10) + "-" + txtNgaySinh.getText().substring(3,5) + "-" + txtNgaySinh.getText().substring(0,2);
                    
                    ps.setString(1, txtMaNhanVien.getText());
                    ps.setString(2, txtTenNhanVien.getText());
                    ps.setString(3,tmp);
                    if(jrbNam.isSelected()) ps.setString(4, "Nam");
                    else ps.setString(4, "Nữ");
                    ps.setString(5, txtSoDienThoaiNV.getText()  );
                    ps.setString(6, txtEmail.getText() );
                    ps.setString(7, jcbChucVu.getSelectedItem().toString() );
                    
                    NhanVienDao nvd = new NhanVienDAOImpl();
                    List<NhanVien> list_nhan_vien = nvd.getListNhanVien();
                    boolean check_maNV = true;
                    
                    String error = "";
                    
                    for(int i=0;i<list_nhan_vien.size();i++)
                    {
                        if(list_nhan_vien.get(i).getMa_nhan_vien().equals(txtMaNhanVien.getText()))
                        {
                            check_maNV = false;
                            error += "Mã nhân viên đã có, hãy nhập mã khác";
                            break;
                        }
                    }
                    
                    if(check_maNV==true) 
                    {
                        ps.executeUpdate();
                        if(joption==0) JOptionPane.showMessageDialog(this,"Đã THÊM thành công");
                        else JOptionPane.showMessageDialog(this,"Đã SỬA thành công");
                        return 1;
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "Mã nhân viên đã có, hãy nhập mã khác");
                        return 0;
                    }
                    
                } catch (Exception ex) {System.out.println(ex.getMessage());}
            }
        } 
        catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Erorr " + e.getMessage());
        }
        return 0;
        
    }
    private String gioiTinhNV;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnQLCV;
    private javax.swing.JButton btnSuaNhanVien;
    private javax.swing.JButton btnThemNV;
    private javax.swing.JButton btnTimKiemNhanVien;
    private javax.swing.JButton btnXoaNhanVien;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JComboBox<String> jcbChucVu;
    private javax.swing.JComboBox<String> jcbTimKiemChucVuNV;
    private javax.swing.JPanel jlbCanhBao;
    private javax.swing.JPanel jpnChucNangNV;
    private javax.swing.JPanel jpnTableQLNV;
    private javax.swing.JRadioButton jrbNam;
    private javax.swing.JRadioButton jrbNu;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSoDienThoaiNV;
    private javax.swing.JTextField txtTenNhanVien;
    private javax.swing.JTextField txtTimKiemMaNV;
    private javax.swing.JTextField txtTimKiemNamSinhNV;
    private javax.swing.JTextField txtTimKiemSDTNV;
    private javax.swing.JTextField txtTimKiemTenNV;
    // End of variables declaration//GEN-END:variables
}
